### ISSUE TITLE
injectAllReactorProjects overwrites non-git properties in reactor projects

### ISSUE THREAD

**Issue by tnaroska** [ktoso/maven-git-commit-id-plugin#108]
The option injectAllReactorProjects should set the git-commit-id related properties in all reactor projects. Right now the code does not only propagate the git properties, but *all* properties set in the current project (i.e. in the pom.xml's <properties> element).
This can overwrite properties completely unrelated to git in other projects leading to unexpected behavior.

**Comment by kwin** [comment]
This is a problem e.g. with the maven-scr-plugin and the maven-bundle-plugin, because they communicate via properties. If those properties are propagated across module boundaries this leads to all kind of errors.
