### ISSUE TITLE
naming conflicts

### ISSUE THREAD

**Issue by derrickburns** [ktoso/maven-git-commit-id-plugin#122]
The default property names that the plugin creates cannot be placed into a JSON structure. For example, these two values cannot be put into a JSON object commit.id

commit.id:2eed44f166489b2f03169a2e2d7f910430ecf7a9
commit.id.abbrev:2eed44f

Instead, the first value should be named as a field in the "commit.id" object. Foe example:

commit.id.full:2eed44f166489b2f03169a2e2d7f910430ecf7a9
commit.id.abbrev:2eed44f

**Comment by derrickburns** [comment]
The[ open source config library from typesafe] (https://github.com/typesafehub/config) will break without this bug fix.

**Comment by TheSnoozer** [comment]
finally fixed with #206
