### ISSUE TITLE
Use commit id extracted by plugin in replace operation during Maven packaging

### ISSUE THREAD

**Issue by rajarshi** [ktoso/maven-git-commit-id-plugin#127]
Hi, not really an issue, but I wasn't sure if this was possible.

Is it possible to have the plugin run, extract the Git commit id (amongst the other stuff it already extracts) and then use the commit id to replace some text in a subset of files, during the packaging phase of a build?

That is, it wouldn't be used to generate a properties file for use during runtime - instead it'd be used to update some files during build time. Is this possible?

**Comment by TheSnoozer** [comment]
Hi @rajarshi,
do you have any updates, questions, comments or concerns on this?

otherwise I would like to close the issue.

Thanks,
