### ISSUE TITLE
git.branch character replacer

### ISSUE THREAD

**Issue by taorg** [ktoso/maven-git-commit-id-plugin#138]
If you work with git-flow, branches get names like this "feature/feature_name"
It would be nice to create jar o ear names with finalNames like this <finalName>${epack}-${git.commit.id.describe}-${git.commit.time}-${git.branch}</finalName>

But the caracter "/" is not valid as filename, it would be nice to have the possibility to replace this character.

**Comment by troinine** [comment]
We have similar issues with other fields thus it would be nice to be able to filter any of the git properties, not just `git.branch`. We use the commit message field and therefore someone can easily end up putting some special characters like double quotes which will fail in our case (Spring Boot app with YAML properties).

**Comment by TheSnoozer** [comment]
From a plugin perspective...what comes close to this feature is:
https://code.google.com/archive/p/maven-replacer-plugin/

The Build Helper Mojo also has something similar:
http://www.mojohaus.org/build-helper-maven-plugin/regex-property-mojo.html#replacement
However I would separate the concerns of validation and replacement...

It might be even useful to restrict the replacement to a specific property:
```
<replacement>
    <property>git.branch</property>
    <token>(?:[^\/]|\/\/)+</token>
    <value>$1-$2</value>
</replacement>
```

Not sure if it would be smarter to include another Mojo or execute it inside the git-commit-id-plugin.
However there should be something like ```failOnUnableToReplacePropertyInfo``

**Comment by TheSnoozer** [comment]
I have implemented this feature and it will be available in version 2.2.3.

Example:
```
<replacementProperties>
  <replacementProperty>
    <property>git.branch</property>
    <token>^([^\/]*)\/([^\/]*)$</token>
    <value>$1-$2</value>
  </replacementProperty>
</replacementProperties>
```

Please checkout the readme for additional details!

**Comment by berniefitz82** [comment]
I'm having a similar issue where local machines git.branch returns just the branch name but during CI/CD it returns origin/branch-name

**Comment by TheSnoozer** [comment]
please create a new issue with all relevant details.
