### ISSUE TITLE
Using GIT properties to generate other properties

### ISSUE THREAD

**Issue by wouter-crowdpark** [ktoso/maven-git-commit-id-plugin#139]
I'm unable to use the GIT properties like ${git.commit.id.abbrev} to create other properties like this:

```
    <properties>
        <test>${git.commit.id.abbrev}</test>
    </properties>
```

IntelliJ also fails to recognize the GIT properties.

Am i missing something here or is this just not possible ?

**Comment by TheSnoozer** [comment]
Hi @wouter-crowdpark ,
do you have any updates, questions, comments or concerns on this?

otherwise I would like to close the issue.

Thanks,

**Comment by Elderry** [comment]
@wouter-crowdpark , I'm also looking for a method to disable Intellij's  `Can not resolve symbol 'git.commit.id'` warning. Any ideas?

**Comment by brushmate** [comment]
You could use a workaround as described here: https://stackoverflow.com/a/37491140/1183192
