### ISSUE TITLE
Additional maintainer

### ISSUE THREAD

**Issue by ktoso** [ktoso/maven-git-commit-id-plugin#158]
Hi guys,
Since I'm not using maven too much recently (the last uhm... 4 years). 
I'd like to ask @TheSnoozer for becoming an additional maintainer on this repository, what would you say about that? :-)

Let's keep this project healthy! :-)

**Comment by TheSnoozer** [comment]
Hi @ktoso,
this is a great honor for me!
I really appreciate this opportunity I would like to join if nobody has any problems with that.

Anybody comments, questions or concerns? :-)

**Comment by dtrucken** [comment]
Thanks for doing this!!!

**Comment by ktoso** [comment]
Adding you to the repo!

**Comment by ktoso** [comment]
And to the readme now as well :-)
Please feel free to reword the section if you'd like to change something in it @TheSnoozer 

https://github.com/ktoso/maven-git-commit-id-plugin/commit/cf57bd1bcaa24261392f195ec1295f210b918421

**Comment by TheSnoozer** [comment]
Hi konrad :)
Thank you for your trust.

The wording is fine. nothing to add there :)
