### ISSUE TITLE
Invalid current release in README.md

### ISSUE THREAD

**Issue by mkordas** [ktoso/maven-git-commit-id-plugin#160]
Main page says:
> The current version is 2.1.14 ([changelist](https://github.com/ktoso/maven-git-commit-id-plugin/issues?q=milestone%3A2.1.14))

while current version is 2.1.13. Is it intended?

**Comment by ktoso** [comment]
Nope, it's a mistake

-- 
Cheers,
Konrad 'ktoso’ Malawski
Akka <http://akka.io> @ Typesafe <http://typesafe.com>
java.pl / geecon.org / krakowscala.pl / lambrakrk.pl / gdgkrakow.pl

2015-03-16 14:37 GMT-07:00 Michał Kordas <notifications@github.com>:

**Comment by mkordas** [comment]
Thanks for fixing :)

**Comment by ktoso** [comment]
no prob, happy hakking
