### ISSUE TITLE
runOnlyOnce problem in aggregator build

### ISSUE THREAD

**Issue by bargainloaf** [ktoso/maven-git-commit-id-plugin#166]
Hey guys,

Great work on the plugin first off. I'm running into the following problem and hoping someone could assist. We have a aggregator pom file that builds several modules. The first of these modules is the parent project which is inherited by every other module.

The problem I have is the following. If the check for runOnlyOnce is true then within the code it checks if the current absolutePath of the bulding project is the same as the execution directory.

This is our module layout

```
/ root directory
  pom.xml <-- Aggregator pom file
  / module a
  / module b
  / module parent
```

The execution directory is / root directory, which means with runOnlyOnce set the plugin will only execute once all other modules has finished executing, which in my case is no good as I need the git information from the first module build.

To explain further what I mean.

``` xml
<modules>
  <module>module parent</module>
  <module>module a</module>
  <module>module b</module>
</modules>
```

I was hoping runOnlyOnce will execute within the module parent project and the properties will be available on every other module build.

I guess my question is am I then doing something wrong with my maven environment? Any help would be appreciated

**Comment by bargainloaf** [comment]
I thought i'll give some feedback on how I managed to get this plugin to work for our circumstance. As I mentioned before my multi-module build config and parent config was sitting in different pom.xml files.

The multi-module build file was sitting in the root and we had a separate sub-module project containing the parent pom all other sub modules will inherit from. What I did is to move the multi module build config into the parent pom.

This is what the structure now looks like
```
/
    / parent-submodule
    / submodule-a
    / submodule-b
    (x) pom.xml <-- This multi module build file has been removed and moved into the pom file
                             of our sub module parent-submodule
```

Now to kick of the build we go into the parent-submodule and do the multi module build. Because all submodules inherit from the parent submodule it builds first and because the execution directory is the same as the current project directory the plugin flag runOnlyOnce works.

**Comment by TheSnoozer** [comment]
Hi @bargainloaf ,
thanks for reporting this issue and letting us know how to fix your problem.
Is there any problem on the git-commit-id-plugin left to fix?
Could you figure out if the plugin behaves as expected or is there anything strange happening in the background?

Again thanks for reporting and sorry for the late response :-)
Thanks,

**Comment by bargainloaf** [comment]
Hi @TheSnoozer,

Someone finally read my comments :). I'm assuming since I reported this issue there hasn't been any releases so I would think that the issue is still around?, but like I mentioned I'm not sure if I was following the correct way to configure a multi module project as I stated in the first comment.

But since moving to the new suggested layout we have not had any problems. One thing I can comment on is sometimes the plugin does take a while to complete during our Maven build. Sometimes even as long as 120 seconds. Otherwise good work, it works great for us.

Thank You

**Comment by bargainloaf** [comment]
Ok had a look and refreshed my memory. This is the problem

```java
    if (runOnlyOnce) {
      if (!session.getExecutionRootDirectory().equals(session.getCurrentProject().getBasedir().getAbsolutePath())) {
        log("runOnlyOnce is enabled and this project is not the top level project, skipping execution!");
        return;
      }
    }
```

What happened with me is the pom.xml file which starts the execution sits in the root folder
```
absolutepath = /c/somedirectory/repository/pom.xml
```

When the code snippet above executes for the first module, which in my case is the parent-module it has the following absolute path
```
absolutepath = /c/somedirectory/repository/parent-module/pom.xml
```

Which means the plugin will not execute as the absolute paths do not match. Only once my aggregator build has completed will the paths finally match and thus the file is created. But this is no use to me by that time as all other modules have already been build

 But as suggested it was probably a problem with the setup of my whole build. There might be no other way to properly address this issue but just to inform people that it could happen and what steps they need to take to prevent it.

**Comment by TheSnoozer** [comment]
Hi @bargainloaf,
thanks for outlining what's going wrong and where the issue is.
I'll debug this when I have some time ;-)
Maybe I'll only add this to the readme to suggest everybody the working workaround.

Mhh your build takes 120+ secs?
Are you using the jgit-implementation?
I had this issue back in a while and therefore the plugin offers two way to extract the git properties.
One way is using the jgit-implementation (default) and the other is by calling the native git-binary.
Maybe give it a shot and try how the performance is with the native-git-binary (I have deployed the native on multiple different platforms and it works really well)

Checkout the README and keep your eye open for ``<useNativeGit>false</useNativeGit>``

**Comment by TheSnoozer** [comment]
I tested this with Version 2.2.2 and there doesn't seem to be a problem.
Setup and code can be reviewed in https://github.com/TheSnoozer/git-commit-id-debugging

Project-Structure:
```
/ root directory
  pom.xml <-- Aggregator pom file
  / submodule-one
  / submodule-two
```

I have defined the maven-git-commit-id-plugin inside the aggregator pom as following:
```
<plugin>
  <groupId>pl.project13.maven</groupId>
  <artifactId>git-commit-id-plugin</artifactId>
  <version>2.2.2</version>
  <executions>
    <execution>
      <goals>
        <goal>revision</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <prefix>git</prefix>
    <verbose>true</verbose>
    <skipPoms>false</skipPoms>
    <runOnlyOnce>true</runOnlyOnce>
    <dotGitDirectory>${project.basedir}/.git</dotGitDirectory>
    <generateGitPropertiesFile>true</generateGitPropertiesFile>
    <generateGitPropertiesFilename>target/classes/git.properties</generateGitPropertiesFilename>
  </configuration>
</plugin>
```

Based on the Readme (https://github.com/ktoso/maven-git-commit-id-plugin) the runOnlyOnce works the following way:
```
                    <!-- @since 2.1.12 -->
                    <!--
                       Use with caution!

                       In a multi-module build, only run once. This means that the plugins effects will only execute once, for the parent project.
                       This probably won't "do the right thing" if your project has more than one git repository.

                       Important: If you're using `generateGitPropertiesFile`, setting `runOnlyOnce` will make the plugin
                       only generate the file in the directory where you started your build (!).

                       The `git.*` maven properties are available in all modules.
                       Default value is `false`.
                    -->
                    <runOnlyOnce>false</runOnlyOnce>
```

Since my parent pom is a reactor-build (``<packaging>pom</packaging>``) I need to set ``<skipPoms>false</skipPoms>`` otherwise the plugin will not execute (not even in the submodule); but thats pretty much what the documentation states. RunOnlyOnce will only have the plugin execute in the parent pom.

Output:
```
[INFO] ------------------------------------------------------------------------
[INFO] Building Git Commit Id Plugin Maven Mojo Debugging 0.0.1 (Parent)
[INFO] ------------------------------------------------------------------------
[INFO] --- git-commit-id-plugin:2.2.2:revision (default) @ git-commit-id-plugin ---
[INFO] Writing properties file to [~/workspace/git-commit-id-debugging/target/classes/git.properties] (for module Git Commit Id Plugin Maven Mojo Debugging)...
[INFO] Git Commit Id Plugin Maven Mojo Debugging] project Git Commit Id Plugin Maven Mojo Debugging

[INFO] ------------------------------------------------------------------------
[INFO] Building submodule-one 0.0.1
[INFO] ------------------------------------------------------------------------
[INFO] --- git-commit-id-plugin:2.2.2:revision (default) @ submodule-one ---
[INFO] runOnlyOnce is enabled and this project is not the top level project, skipping execution!


[INFO] ------------------------------------------------------------------------
[INFO] Building submodule-two 0.0.1
[INFO] ------------------------------------------------------------------------
[INFO] --- git-commit-id-plugin:2.2.2:revision (default) @ submodule-two ---
[INFO] runOnlyOnce is enabled and this project is not the top level project, skipping execution!
```
