### ISSUE TITLE
slf4j version conflicts

### ISSUE THREAD

**Issue by dan-leavitt** [ktoso/maven-git-commit-id-plugin#170]
Building with this plugin causes dependency conflicts that prevent my app from running in tomcat.  Could this project be updated to use more recent slf4j versions or is there something I can do to control this?

```
+- pl.project13.maven:git-commit-id-plugin:jar:2.1.12:compile
[INFO] |  \- org.apache.maven:maven-core:jar:2.2.1:compile
[INFO] |     +- org.apache.maven.wagon:wagon-webdav-jackrabbit:jar:1.0-beta-6:runtime
[INFO] |     |  +- org.apache.jackrabbit:jackrabbit-webdav:jar:1.5.0:runtime
[INFO] |     |  |  \- (org.slf4j:slf4j-api:jar:1.5.3:runtime - omitted for conflict with 1.7.7)
[INFO] |     |  \- org.slf4j:slf4j-nop:jar:1.5.3:runtime
[INFO] |     |     \- (org.slf4j:slf4j-api:jar:1.5.3:runtime - omitted for conflict with 1.7.7)
[INFO] |     \- org.slf4j:slf4j-jdk14:jar:1.5.6:runtime
[INFO] |        \- (org.slf4j:slf4j-api:jar:1.5.6:runtime - omitted for conflict with 1.7.7)
```

The 1.7.7 version comes from here:

```
org.springframework.data:spring-data-jpa:jar:1.7.0.RELEASE:compile
[INFO] \- org.springframework.data:spring-data-jpa:jar:1.7.0.RELEASE:compile
[INFO]    +- org.springframework.data:spring-data-commons:jar:1.9.0.RELEASE:compile
[INFO]    |  \- (org.slf4j:slf4j-api:jar:1.7.7:compile - omitted for duplicate)
[INFO]    +- org.slf4j:slf4j-api:jar:1.7.7:compile
[INFO]    \- org.slf4j:jcl-over-slf4j:jar:1.7.7:runtime
[INFO]       \- (org.slf4j:slf4j-api:jar:1.7.7:runtime - omitted for duplicate)
```

**Comment by ktoso** [comment]
Thanks for the info. In general these things should be able to be controlled using `<dependencyManagement>` sections where you override which version should be picked.

Here's a good link on the topic http://stackoverflow.com/questions/3937195/maven-how-to-override-the-dependency-added-by-a-library

**Comment by dan-leavitt** [comment]
On 3/24/15 6:00 AM, Konrad Malawski wrote:
>
> Thanks for the info. In general these things should be able to be 
> controlled using |<dependencyManagement>| sections where you override 
> which version should be picked.
>
> Here's a good link on the topic 
> http://stackoverflow.com/questions/3937195/maven-how-to-override-the-dependency-added-by-a-library
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ktoso/maven-git-commit-id-plugin/issues/170#issuecomment-85428839>.
>
Thanks for the quick response.  Using that advise I think I have worked 
around this by specifying a newer maven-core package before the 
git-commit-id-plugin.   That's not the newest though, as it gave me 
other issues elsewhere with the annotation processing.

     <dependency>
       <groupId>org.apache.maven</groupId>
       <artifactId>maven-core</artifactId>
       <version>3.0</version>
     </dependency>
     <dependency>
       <groupId>pl.project13.maven</groupId>
       <artifactId>git-commit-id-plugin</artifactId>
       <version>2.1.13</version>
     </dependency>

**Comment by TheSnoozer** [comment]
You can also just exclude the conflicting packages:

```
<dependencies>
    <dependency>
       <groupId>pl.project13.maven</groupId>
       <artifactId>git-commit-id-plugin</artifactId>
       <version>2.1.13</version>
			<exclusions>
				<!-- because of using XXX -->
				<exclusion>
					<artifactId>org.slf4j</artifactId>
					<groupId>slf4j-jdk14</groupId>
				</exclusion>
			</exclusions>
		</dependency>
</dependencies>
```

Furthermore you can set a so called scope for a dependeny. This tells maven where you need a module (e.g. only for testing, compile, or fur runtime)
example:
```
   <dependency>
       <groupId>pl.project13.maven</groupId>
       <artifactId>git-commit-id-plugin</artifactId>
       <version>2.1.13</version>
       <scope>compile</scope>
     </dependency>
```
this can also resolve some issues especially for runtime :)

**Comment by TheSnoozer** [comment]
Hi,
I would like to close the issue due to the fact that there is some sort of maven solution available.
This happens everyday and is a normal dependency conflict.

However, if there are some questions unanswered feel free to reopen the ticket and ask.

Thanks,
