### ISSUE TITLE
Plugin should use slf4j for logging, because it's more configurable

### ISSUE THREAD

**Issue by binkley** [ktoso/maven-git-commit-id-plugin#191]
The plugin ignores `MAVEN_OPTS=-Dorg.slf4j.simpleLogger.defaultLogLevel=warn` and displays log messages prefixed with `[info]` (_sic_).

**Comment by ktoso** [comment]
true, because it's not using slf4j but printlines... I guess we should change this finally.

For the time being: please set `<verbose>false</verbose>` in your pom, refer to the README for more info

**Comment by ktoso** [comment]
I changed the title of the issue to describe what needs to be done here. 
If you would like to help out a PR would be very much appreciated! 

Thanks for reporting and maybe for the PR in advance(?)! :-)

**Comment by ktoso** [comment]
Resolved by #194
