### ISSUE TITLE
Open Maven issue we should keep on the watch list

### ISSUE THREAD

**Issue by TheSnoozer** [ktoso/maven-git-commit-id-plugin#199]
I thought it's time to open some sort of watch list for our Maven problems...
- [ ] Problem with Required-Parameters and Default-Values in Nested Objects for Plugin-Parameters (https://issues.apache.org/jira/browse/MNG-5725)
- [ ] Maven 3.0.5 / 3.3.3 breaks plugins with some dependencies on the class path / slf4j (https://issues.apache.org/jira/browse/MNG-5787)
- [ ] Maven-Plugin's getLog() ignores -Dorg.slf4j.simpleLogger.defaultLogLevel=warn (https://issues.apache.org/jira/browse/MNG-5835)
- [ ] Inconsistency for dynamic property replacement while using Maven's Plugin Prefix Resolution
(https://issues.apache.org/jira/browse/MNG-6260)
Currently we have a workaround for all of them but should keep an eye open if someday a maven solution is shipped.

**Comment by ktoso** [comment]
Thanks!

-- 
Konrad 'ktoso’ Malawski
Akka @ Typesafe
java.pl / geecon.org / krakowscala.pl / lambdakrk.pl

On 3 June 2015 at 22:07:34, TheSnoozer (notifications@github.com) wrote:

I thought it's time to open some sort of watch list for our Maven problems...

 Problem with Required-Parameters and Default-Values in Nested Objects for Plugin-Parameters (https://issues.apache.org/jira/browse/MNG-5725)
 Maven 3.0.5 / 3.3.3 breaks plugins with some dependencies on the class path / slf4j (https://issues.apache.org/jira/browse/MNG-5787)
 Maven-Plugin's getLog() ignores -Dorg.slf4j.simpleLogger.defaultLogLevel=warn (https://issues.apache.org/jira/browse/MNG-5835)
Currently we have a workaround for all of them but should keep an eye open if someday a maven solution is shipped.

**Comment by TheSnoozer** [comment]
I don't see a point anymore why we should keep the SLFJ on that list.
We fixed that with
https://github.com/ktoso/maven-git-commit-id-plugin/issues/230 / https://github.com/ktoso/maven-git-commit-id-plugin/pull/233

**Comment by TheSnoozer** [comment]
Graveyarding this....we have workarounds for all cases and those are reported...maven always makes trouble...
