### ISSUE TITLE
Maybe introduce a test-coverage Badge to the Readme?

### ISSUE THREAD

**Issue by TheSnoozer** [ktoso/maven-git-commit-id-plugin#207]
I have seen a couple of projects on github using a test-coverage badge on the readme.
It's kind of nice to have but not required at all....

Example:
[![Coverage Status](https://coveralls.io/repos/letsencrypt/letsencrypt/badge.svg?branch=master)](https://coveralls.io/r/letsencrypt/letsencrypt?branch=master)

Code:

```
[![Coverage Status](https://coveralls.io/repos/letsencrypt/letsencrypt/badge.svg?branch=master)](https://coveralls.io/r/letsencrypt/letsencrypt?branch=master)
```

Anybody interested to introduce the same for the git-commit-id-plugin?

```
https://coveralls.io/pricing
Coveralls is and will always be free for open source projects
```

**Comment by ktoso** [comment]
I don't mind, can give it a shot

**Comment by TheSnoozer** [comment]
graveyard this.

**Comment by ktoso** [comment]
Okey, and thanks for all the cleaning up :)

**Comment by TheSnoozer** [comment]
not a problem....was kinda inactive due to master's thesis, moving, new job, .... = no time ;)

**Comment by ktoso** [comment]
Congratulations then! :-) I moved too in the last months, now Japan based 🌊  So sorry for weird delays in replies in case you'd ping :)
