### ISSUE TITLE
Skip execution based on presence of file

### ISSUE THREAD

**Issue by tweise** [ktoso/maven-git-commit-id-plugin#209]
This option would be useful to limit execution to once after clean. The behavior cannot be accomplished via profile since the activation condition is evaluated before clean and not at time of execution.

**Comment by TheSnoozer** [comment]
Well you can also deactivate the git-commit-id-plugin directly when the profile is activated. Then there would be no need to check for some magic files...Also I think it would just be to complicated and raise race-conditions to check for the presence a local file....

```xml
<profile>
      <id>demo</id>
      <build>
        <plugins>
          <plugin>
            <groupId>pl.project13.maven</groupId>
            <artifactId>git-commit-id-plugin</artifactId>
            <version>${project.version}</version>
            <executions>
              <execution>
                <goals>
                  <goal>revision</goal>
                </goals>
              </execution>
            </executions>
            <configuration>
              <skip>true</skip>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
```

**Comment by tweise** [comment]
The idea was to only generate the revision info when the file wasn't already generated (for incremental build/development mode).

**Comment by TheSnoozer** [comment]
Hi @tweise,
as far as I know it should work fine that the current version of the plugin will not regenerate the properties-file if it's present and up-to-date.
If I build the current bit-commit-id-module with ``mvn package -Pdemo -Dmaven.test.skip=true`` I'll get the following output:
```
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - Reading exising properties file [ /home/lange/Downloads/maven-git-commit-id-plugin/target/testing.properties ] (for module  Git Commit Id Plugin Maven Mojo )...
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - Properties file [ /home/lange/Downloads/maven-git-commit-id-plugin/target/testing.properties ] is up-to-date (for module  Git Commit Id Plugin Maven Mojo )...
```
However, if you are using clean, there is no file available and the plugin needs to generate a new file.
Also if you commit new stuff, it should also be regenerated.

**Comment by TheSnoozer** [comment]
Hi @tweise,
could this solve your problem?

**Comment by tweise** [comment]
Actually, I'm looking to skip execution entirely if the file was already generated. I was trying to use the skip property and profile activation based on presence of the generated file. That works except in the case of clean, where the file is blown away after the profile got activated and skip was already set.

That's the reason I created #208 - it would allow me to set the skip property after clean was executed.

**Comment by TheSnoozer** [comment]
Maybe it's just too late to get the use-case of this... 
However a clean is actually supposed to clean everything including the file that was generated by the git-commit-id-plugin. When the file is gone you can't obtain any version informations out of it. 
Also if the file is present the plugin should check if it's up to date, otherwise you'll get old version informations in whereever you use them.

So in case you don't need the file to be generated on a specific condition; wrap this in a profile and skip the execution of the plugin entirely. Also as outlined in #208 you could go the suggested workaround to introduce your custom tailored switch to deactivate the plugin in whatsoever usecases.

Example:
```xml
<!-- global properties for the pom -->
<properties>
  <!-- by default we would like to execute the plugin -->
  <git.commit.plugin.skip>true</git.commit.plugin.skip>
</properties>

<!-- global execution definition of the plugin -->
<plugin>
  <groupId>pl.project13.maven</groupId>
  <artifactId>git-commit-id-plugin</artifactId>
  <executions>
    <execution>
      <goals>
        <goal>revision</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <skip>${git.commit.plugin.skip}</skip>
  </configuration>
</plugin>

<!-- customer Profile -->
<profile>
  <id>demo</id>
  <properties>
    <git.commit.plugin.skip>true</git.commit.plugin.skip>
  </properties>
</profile>

```

Either when you activate the profile ``demo`` with ``mvn clean package -Pdemo`` or if you set the property ``git.commit.plugin.skip`` via command-line ``mvn clean package -Dgit.commit.plugin.skip=true`` the execution of the plugin is skipped.

**Comment by tweise** [comment]
The solution I was looking for requires dynamic behavior and cannot be accomplished via profiles. Your example is the setup I'm currently using. It cannot handle the case where clean removes the file, it won't regenerate it during package in the same run. Command line parameter is a workaround. The better solution would be to detect the skip value during execution, but for that the plugin would need to be able to handle a property directly.

**Comment by TheSnoozer** [comment]
Hi @tweise,
this overall issue sounds like you would like to something special if you have a magic file in your repository. Maven is build to create repeatable builds and as a general thumb rule doing something special whether a file is present of not. 
However, the maven-profiles can be activated by default with when certain conditions are true.

Example profile that will be activated if a specific file is present (this will then also skip the execution of the git-commit-id-plugin):
```xml
   <profile>
        <id>disable-git-commit-id-plugin</id>
        <activation>
            <file>
		<!-- ${basedir}/src/main/resources/magic.file -->
                <exists>${basedir}/LICENSE</exists>
            </file>
        </activation>
        <build>
            <plugins>
		 <plugin>
            		<groupId>pl.project13.maven</groupId>
            		<artifactId>git-commit-id-plugin</artifactId>
            		<version>${project.version}</version>
			<configuration>
              			<skip>true</skip>
            		</configuration>
		</plugin>
                <plugin>
                    <artifactId>maven-antrun-plugin</artifactId>
		    <version>1.8</version>
                    <executions>
                        <execution>
                            <phase>generate-resources</phase>
                            <goals>
                                <goal>run</goal>
                            </goals>
                            <configuration>
                                <target>
                                    <echo>** WARNING: SKIPPING EXECUTION OF git-commit-id-plugin</echo>
                                </target>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </build>
    </profile>
```

Note the execution of the maven-antrun-plugin is not necessary, but this could display some message to you to warn you that the property-file is not generated.

**Comment by TheSnoozer** [comment]
I think in this thread there should be enough different ways to actually conquer what was requested.
Additionally I think the plugin works as expected and therefore would close this issue.
