### ISSUE TITLE
Maybe add a switch to generate the git.commit.id the "old" way

### ISSUE THREAD

**Issue by TheSnoozer** [ktoso/maven-git-commit-id-plugin#211]
I'm currently not really happy with the solution we have for the changing one of the major properties from ``git.commit.id`` to ``git.commit.id.full`` (related to https://github.com/ktoso/maven-git-commit-id-plugin/issues/122 and https://github.com/ktoso/maven-git-commit-id-plugin/commit/80fced8db322b1a1ccead59ca1ed8fed93742cec).

I think a way more better solution would be to include a switch (call that generateCommitIdOldFashioned) that's by default set to true.

switch set to true: will output everything as it was (so will generate the properties with ``git.commit.id``) and also will output an WARNING that using the switch set to true is deprecated.

switch set to false (manual adjustment): will output everything the new fashioned way (so will generate the properties with ``git.commit.id.full``) and no further WARNING/ERROR-Messages will be displayed to the user.

In this way, the user can choose himself whenever he would like to do the migration and we not just kill the backwards compatibility.

**Comment by ktoso** [comment]
I agree the current style is not very nice, though not sure if we can afford breaking existing adjusted clients... will review thr PR

**Comment by TheSnoozer** [comment]
fixed by https://github.com/ktoso/maven-git-commit-id-plugin/pull/212
