### ISSUE TITLE
Update jgit version to v4.0.1.201506240215-r

### ISSUE THREAD

**Issue by mih-kopylov** [ktoso/maven-git-commit-id-plugin#216]
Here's the jgit commit that fixes IOException https://github.com/eclipse/jgit/commit/ec6ec3b10fb1ef8dd73a499d0b1f7a7d711b84dd
Here's the jgit release with the fix
https://github.com/eclipse/jgit/releases/tag/v4.0.1.201506240215-r

**Comment by ktoso** [comment]
Great! Would you like to submit a Pull Request updating the version?

**Comment by TheSnoozer** [comment]
Is https://github.com/ktoso/maven-git-commit-id-plugin/issues/203 the same Problem?
If so we should think about releasing the 2.2.0

Workaround:
UniversalMediaServer/UniversalMediaServer#627 (comment)

**Comment by ktoso** [comment]
Yeah, let's release once jgit version bumped :+1:

**Comment by TheSnoozer** [comment]
Updated the version; will run a quick test under windows to make sure everything is stable....
PR eta 20 Mins

**Comment by TheSnoozer** [comment]
still some failing tests here. not sure if it's my environment. Will deploy another Windows VM....:-(
Stay tuned..

**Comment by TheSnoozer** [comment]
Updated the title due to the fact that the NPE is fixed in the jgit version that was introduced in #203.

**Comment by ktoso** [comment]
Resolved by https://github.com/ktoso/maven-git-commit-id-plugin/pull/233
