### ISSUE TITLE
Release 2.2.0

### ISSUE THREAD

**Issue by ktoso** [ktoso/maven-git-commit-id-plugin#219]
Seems like we may want to include https://github.com/ktoso/maven-git-commit-id-plugin/issues/216 but otherwise are ready to ship 2.2.0, WDYT @TheSnoozer?

**Comment by TheSnoozer** [comment]
I think we are ready to ship the 2.2.0. 
As far I can tell the #216 is only a ticket for upgrading the jgit-implementation. The Path-Bug is already fixed in the implementation we are currently using....as a result keep the issue open (we should upgrade soon), but I do not see the need to upgrade for the 2.2.0.

Hopefully will have some time over the weekend to debug this.
Currently buried in work ;-)

**Comment by ktoso** [comment]
Okey, thanks for the heads up!
I'll cut the 2.2.0 soon then.

-- 
Cheers,
Konrad 'ktoso’ Malawski
Akka <http://akka.io> @ Typesafe <http://typesafe.com>
java.pl / geecon.org / krakowscala.pl / lambrakrk.pl / gdgkrakow.pl

2015-09-25 18:06 GMT+02:00 TheSnoozer <notifications@github.com>:

**Comment by ktoso** [comment]
I've pushed the release. Will do release notes in the evening.

**Comment by TheSnoozer** [comment]
awsome!

**Comment by ktoso** [comment]
Updated the readme with the right version numbers as well :)

**Comment by ktoso** [comment]
Thanks @TheSnoozer and everyone involved in this one!

**Comment by TheSnoozer** [comment]
Thank you @ktoso. You made this all possible :-J

**Comment by TheSnoozer** [comment]
@ktoso, could you check if the deployment got stock somewhere?
Can't find the jar on https://search.maven.org/#search|gav|1|g%3A%22pl.project13.maven%22%20AND%20a%3A%22git-commit-id-plugin%22

Thanks :-)

**Comment by ktoso** [comment]
Hah excellent catch, forgot to click `release` (step 2) in sonatype (did click `close` (step 1))

**Comment by ktoso** [comment]
Pushed now, should be online in a few minutes

**Comment by ktoso** [comment]
Done: http://repo1.maven.org/maven2/pl/project13/maven/git-commit-id-plugin/2.2.0/ 
Thanks for the reminder @TheSnoozer !

**Comment by TheSnoozer** [comment]
awesome! Thx :-)
