### ISSUE TITLE
git.dirty return always true (useNativeGit=true)

### ISSUE THREAD

**Issue by Puccet** [ktoso/maven-git-commit-id-plugin#236]
I'm experiencing a strange bug, the git.dirty property is always true no matter what the real git status is

Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c; 2015-03-13T21:10:27+01:00)
Maven home: /usr/local/apache-maven
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre
Default locale: it_IT, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.2", arch: "x86_64", family: "mac"

java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

Here's the pom.xml details

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.1</version>
        </dependency>
        <dependency>
            <groupId>org.scream3r</groupId>
            <artifactId>jssc</artifactId>
            <version>2.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.3.2</version>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.4</version>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.10</version>
        </dependency>
        <dependency>
            <groupId>de.taimos</groupId>
            <artifactId>gpsd4java</artifactId>
            <version>1.3</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>2.2.0 </version>
                <executions>
                    <execution>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <useNativeGit>true</useNativeGit>
                    <prefix>git</prefix>
                    <dateFormat>dd.MM.yyyy @ HH:mm:ss z</dateFormat>
                    <verbose>true</verbose>
                    <dotGitDirectory>${project.basedir}/.git</dotGitDirectory>
                    <generateGitPropertiesFile>true</generateGitPropertiesFile>
                    <generateGitPropertiesFilename>src/main/resources/it/casram/git.properties
                    </generateGitPropertiesFilename>
                    <gitDescribe>
                        <tags>true</tags>
                        <skip>false</skip>
                        <abbrev>40</abbrev>
                        <dirty>-experimental</dirty>
                        <forceLongFormat>false</forceLongFormat>
                    </gitDescribe>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.2</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>it.casram.ecomodule.App</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

![1 puccet bash 2016-01-13 16-01-07](https://cloud.githubusercontent.com/assets/5746022/12297782/07661eb4-ba0f-11e5-869a-5e3ac9f649e6.png)
![1 puccet bash 2016-01-13 16-01-41](https://cloud.githubusercontent.com/assets/5746022/12297783/07862916-ba0f-11e5-878d-7bef5e444917.png)
![1 puccet bash 2016-01-13 16-02-02](https://cloud.githubusercontent.com/assets/5746022/12297784/0788a240-ba0f-11e5-95e4-3dd215c80bf4.png)

**Comment by coladict** [comment]
Does it still do it if you don't have `<useNativeGit>true</useNativeGit>` (using default jgit)? I use the default setting for that and it detects it properly.

**Comment by Puccet** [comment]
It does if i use <useNativeGit>false</useNativeGit> if I use it to "true" there's an inconsistency because it report the state dirty but the resulting name is not reporting it (no -dirty is appended to the tag name), please consider this was tested in a just cloned folder so it's really annoying due to fact that it prevents to use any automation.

during the build the target folder and a git.properties file are created but both are in the .ignore list.

**Comment by coladict** [comment]
Then, essentially this is the same as issue #234. Half of your problem can be solved by using jgit, the other half using `<generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>`. This is a better way to generate the file than the one suggested, without adding more to your `.gitignore`. I'll make the change in the documents for it and do a PR.

**Comment by Puccet** [comment]
Hi thanks very much for the answer but honestly did understood it completely, I was assuming jgit is used when `<useNativeGit>false</useNativeGit>` is set, but in this case it report the status as dirty anyway,
using `<generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>` is awkward because the file is used also during debug not only at build time so i should create it, debug, remove  and build, last but not least the target folder is also generated during the build so it's not an option.
What i think is Jgit should conforms to the git behavior and return consistent behavior, that's the right solution.

**Comment by ktoso** [comment]
A PR with tests would be welcome to resolve this issue, thanks in advance

**Comment by Puccet** [comment]
I've found [here](https://github.com/ktoso/maven-git-commit-id-plugin/issues/47) that the command

git clean -dfx solve the inconsistency, I've issued the command once and now ti seems to work properly, I'll investigate deeper as soon as I'll have more time.

**Comment by TheSnoozer** [comment]
RELATED TO:  https://github.com/ktoso/maven-git-commit-id-plugin/issues/234

**Comment by TheSnoozer** [comment]
I found the actual problem and already fixed it.
The root cause for this was buried in the usage of the ProcessBuilder that is used when we check if the repository is dirty.
In short what happend is that we somehow ended up calling the check for 'git status -s' wrongly and the result of the command was always printing the usage manual. Since for the status we only check if there was a return value or not, the tool assumed that the repository was in a dirty state since the return of the check was not empty...took a while to catch this one...;-)

**Comment by ktoso** [comment]
Great catch, thanks @TheSnoozer !
