### ISSUE TITLE
why ${git.branch} returns git commit id?

### ISSUE THREAD

**Issue by missedone** [ktoso/maven-git-commit-id-plugin#239]
hi folks

i'm using maven-git-commit-id-plugin 2.2.0 release.

i have the [git.properties](https://github.com/cbeust/testng-eclipse/blob/master/testng-eclipse-plugin/src/main/resources/git.properties) as below:
```
git.branch=${git.branch}
git.commit.id=${git.commit.id}
git.build.version=${git.build.version}
```

but the output `git.branch` has the same value as `git.commit.id`: 
```
git.commit.id=2aa34716df7ac8385678e6bea9eb5423c41e35b4
git.branch=2aa34716df7ac8385678e6bea9eb5423c41e35b4
git.build.version=6.9.11-SNAPSHOT
```

is it be designed? it looks to me is a bug that i expect `git.branch` returns branch name like `master`

**Comment by ktoso** [comment]
What does native git say for that state of the repo?
`git branch` will return a SHA if it's detached from any branch ("detached head state"), in which case the above is valid.

**Comment by missedone** [comment]
right, that make sense then,

i got the git.branch as commit id in the travis-ci build which use the detached mode.
i just double checked on my local, it have the correct git.branch value.

**Comment by ktoso** [comment]
Thanks for checking :-)
Happy hakking!
