### ISSUE TITLE
maven-git-commit-id-plugin breaks resources and war webResources filtering

### ISSUE THREAD

**Issue by o6l6** [ktoso/maven-git-commit-id-plugin#249]
Try running 'mvn package -P dev' and check out the two files in the war: ${db.host} will not have been replaced in either of them. Comment out the git plugin or even just its single <includeOnlyProperty> element and resource filtering works properly once more.
[bug1.zip](https://github.com/ktoso/maven-git-commit-id-plugin/files/297058/bug1.zip)

[Uploading bug1.zip…]()

**Comment by TheSnoozer** [comment]
Please add ``<injectAllReactorProjects>true</injectAllReactorProjects>`` to the configuration of the maven-git-commit-id-plugin and it should work like a charm.

Thanks,

**Comment by TheSnoozer** [comment]
Assuming issue was resolved.
