### ISSUE TITLE
Does not work with new Maven versions

### ISSUE THREAD

**Issue by Nicolai82** [ktoso/maven-git-commit-id-plugin#257]
When using this plugin with Maven version 3.2.1, I get this error message:

Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.1:revision (get-the-git-infos) on project testproject: The plugin pl.project13.maven:git-commit-id-plugin:2.2.1 requires Maven version [3.1.1,) 

EDIT: Works with the latest version (3.3.9)

**Comment by ktoso** [comment]
Cool, must have been something weird in Maven. Thanks for reporting nevertheless

**Comment by AlekEagleYT** [comment]
I'm on debian and IDK how to update the plugin/Maven
