### ISSUE TITLE
Feature request: Pretty-Print json

### ISSUE THREAD

**Issue by micw** [ktoso/maven-git-commit-id-plugin#265]
It would be cool, if the json would be more human readable (aka pretty printed). I use to have a version.json in my dists, that is read automatically - so it could be easily read by humans as well.

**Comment by ktoso** [comment]
Should not be hard to implement, I'd suggest you'd try doing a PR which implements this - WDYT?
Happy to accept if such PR comes in.

**Comment by micw** [comment]
Here you go. Sorry, my eclipse re-ordered the imports, the actual change is just one line.

**Comment by ktoso** [comment]
Cool, thanks!

**Comment by micw** [comment]
Thank you for merge. I'd be happy to see a new release with this feature ;)
