### ISSUE TITLE
UTF-8 characters in properties file format generates issue in filtered resources

### ISSUE THREAD

**Issue by mkrivan** [ktoso/maven-git-commit-id-plugin#270]
I am just started to use your plugin for generating git info properties but I had some problems because of non ascii characters used in git comments. Example: git.commit.user.name=Kriván Miklós

The generated git.properties file I have planned to use for filtering one resource file called release.html. Everything works perfect except the non ascii characters (encoded in UTF-8) appears after inserting into the template like double strange latin characters.

I was thinking and searching on Google and found that properties file should not use utf-8 encoding but unicode escaping instead.

When I have changed the lines in the generated properties file into the unicode escaped form, the resource filtering worked as needed and the characters displayed correct. I always use UTF-8 sourceEncoding in maven projects.

If I have translate the plugin's generated properties file with native2ascii utility the resulted properties file is the expected one.

Would you help with the maven plugin to generate the properties file in unicode escaped form?
Or do you have some kind of parameter for that?

Thanks in advance.

**Comment by mkrivan** [comment]
I did some more experiments with this plugin. The problem only occurs when I create the git.properties file with the plugin and I use it for filtering resources. If I just use the default generateGitPropertiesFile = false parameter the property values appears in the right form in the filtered resources. I also have downloaded the plugin git master branch and I have tried something. Now I see where can I modify a little for generating property file correctly for java. If I change the localProperties.store(Writer out, String comment) method call into localProperties.store(OutputStream out, String comment) then the UTF-8 property values stored in the properties file correctly appears with the unicode escape sequence. But still I do some investigation what is good for me and what is really need to take into account. Thanks for your efforts in this plugin it is extremely useful.

**Comment by mkrivan** [comment]
I have created a fork and created a pull request with my suggestion.

**Comment by ktoso** [comment]
Cool, thanks for the PR. I'll have a look soon.

-- 
Konrad 'ktoso’ Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>
<http://java.pl/>java.pl / geecon.org / krakowscala.pl / lambdakrk.pl /
sckrk.com

On 30 December 2016 at 17:43:26, Miklós Kriván (notifications@github.com)
wrote:

I have created a fork and created a pull request with my suggestion.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ktoso/maven-git-commit-id-plugin/issues/270#issuecomment-269792904>,
or mute the thread

**Comment by mkrivan** [comment]
Dear Konrad, is that possible that there are some project test cases which only successful on linux and not on windows? the special character handling always fail even if I run chcp 65001 on windows. What can be wrong? What should I do different on windows 10? Now I am continue to work in bash on windows 10. In this case the test cases run smooth. Thx for your suggestion.

**Comment by mkrivan** [comment]
I have found a solution for "Unable to delete sandbox" :-) it was a jGit issue on Windows when objects are packed in repository. Just a small thing. No i have only one more issue with the dirty flag. It is a bit strange it looks jGit and native Git (of course on Windows only) behaves differently.

So I do more work on this. I would like to understand a little bit what is this.

Would you help to explain what is the original idea behind the dirty status? Maybe it helps a little bit to analyze the situation. Maybe is there any relation with the plugin repo status and the resources examples repo? I will try to continue this direction.

**Comment by ktoso** [comment]
dirty means files added to the index were modified. it's the state you're in if status shows you have changes.

**Comment by mkrivan** [comment]
Ok I see the dirty status using command line execution. It looks that something is strange when running the code on Windows of course. The native git case shows dirty when it is not dirty. I will continue to search for the explanation :-)

**Comment by mkrivan** [comment]
Thx for the feedback we just typed at the same time :-)

**Comment by mkrivan** [comment]
I did it. Everything works perfect from Windows as well. I have created test case for the properties file as well. Both the nativeGit and jGir works. Also I have tested from Linux.

Should I need to create a new pull request or it is enough that I have pushed onto my fork?
Thx. for your help.

**Comment by ttamirt** [comment]
I'm using v2.2.2 of the plugin, but it doesn't display unicode characters properly. I'm using Jenkins on centos to build my project. Is there any settings or configuration that I'm missing?

**Comment by cgoeller** [comment]
@ktoso Could you please release a new version which inludes the changes from mkrivan?
It seems the version 2.2.2 does not include the pull request

**Comment by ktoso** [comment]
Well l since it isn't merged it's not in a release, correct :-)
I'll try to get to it soon, but in the middle of moving between continents so a bit chaotic on my end.

**Comment by TheSnoozer** [comment]
is this still open?

**Comment by TheSnoozer** [comment]
https://github.com/ktoso/maven-git-commit-id-plugin/pull/271

**Comment by ttamirt** [comment]
When will **2.2.3** get released?
