### ISSUE TITLE
Where is 2.2.2 ?

### ISSUE THREAD

**Issue by uportalis** [ktoso/maven-git-commit-id-plugin#272]
Hi

The README says that the latest released version is 2.2.1.
The usage example uses 2.2.1 but also contains parameters introduced in 2.2.2.

Moreover, it looks like some people are using 2.2.2 but I can't find it on Maven Central nor on Sonatype repository (where the snapshot versions should be according to the README).

Can you please clarify if 2.2.2 can be downloaded already or still is a work in progress (and do you have an estimated target delivery date)?

BTW, thank you for this plugin. It is exactly what I was looking for (and waiting for 2.2.2 for the validation features).

rgds,
Louis

**Comment by ktoso** [comment]
Released *now*, thanks for the ping.
