### ISSUE TITLE
Plugin takes 10-20x longer in submodules

### ISSUE THREAD

**Issue by electrum** [ktoso/maven-git-commit-id-plugin#273]
We use the plugin in [Presto](https://github.com/prestodb/presto) which is a multi-module Maven project with a single Git repository. The plugin is very fast for the root module (~100ms) but takes 1-2 seconds in submodules.

If this is due to walking the directory hierarchy to find find the `.git` directory (seems unlikely since all modules are in the root directory), we'd be fine with explicitly configuring the directory which contains the `.git` directory.

```
$ mvn initialize -Dbuildtime.output.log -pl .,presto-array,presto-bytecode,presto-spi
...
[INFO] Build Time Summary:
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] presto-root
[INFO]   git-commit-id-plugin:revision (default) .................. [0.084s]
[INFO] presto-bytecode
[INFO]   git-commit-id-plugin:revision (default) .................. [1.207s]
[INFO] presto-spi
[INFO]   git-commit-id-plugin:revision (default) .................. [1.557s]
[INFO] presto-array
[INFO]   git-commit-id-plugin:revision (default) .................. [1.233s]
[INFO] ------------------------------------------------------------------------

**Comment by ktoso** [comment]
Please provide a reproducer of profile the plugin :-)
Help us, help you.

PR also welcome if you would have the time, thanks!

**Comment by electrum** [comment]
How can I help reproduce? You can reproduce by cloning the Presto project and running the Maven command I showed.

**Comment by electrum** [comment]
It looks like the plugin doesn't do anything for the root module (probably due to packaging being `pom`). So that explains why it's so much faster.

**Comment by TheSnoozer** [comment]
If you want to change the behaviour use ``<skipPoms>false</skipPoms>``

from the docs:
```
<!--
                        this is true by default; You may want to set this to false, if the plugin should run inside a
                        <packaging>pom</packaging> project. Most projects won't need to override this property.

                        For an use-case for this kind of behaviour see: https://github.com/ktoso/maven-git-commit-id-plugin/issues/21
                    -->
                    <skipPoms>true</skipPoms>
```
