### ISSUE TITLE
URISyntaxException: Illegal character in scheme name at index 0: [git@...

### ISSUE THREAD

**Issue by sshcherbakov** [ktoso/maven-git-commit-id-plugin#274]
Im getting the following exception when building using git-commit-id-plugin version 2.2.2:
````
			<plugin>
				<groupId>pl.project13.maven</groupId>
				<artifactId>git-commit-id-plugin</artifactId>
			</plugin>
````
The error message:
````
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.2:revision (default) on project demo: Could not complete Mojo execution... java.net.URISyntaxException: Illegal character in scheme name at index 0: [git@mygithost:10022]:my-group/my-sample-project.git -> [Help 1]
````
Exactly same project builds completely fine with the plugin version 2.1.15:
````
			<plugin>
				<groupId>pl.project13.maven</groupId>
				<artifactId>git-commit-id-plugin</artifactId>
				<version>2.1.15</version>
			</plugin>
````

Please note, that the git URI `[git@mygithost:10022]:my-group/my-sample-project.git` is fully valid and works well from my git console. I also probably cannot omit the square bracket in the URI because of the non-default URI port.

**Comment by vanSabben** [comment]
I have the same problem with version 2.2.2.

**Comment by TheSnoozer** [comment]
https://www.kernel.org/pub/software/scm/git/docs/git-clone.html#URLS

In general, URLs contain information about the transport protocol, the address of the remote server, and the path to the repository. Depending on the transport protocol, some of this information may be absent.
Git supports ssh, git, http, and https protocols (in addition, ftp, and ftps can be used for fetching, but this is inefficient and deprecated; do not use it).
The native transport (i.e. git:// URL) does no authentication and should be used with caution on unsecured networks.

The following syntaxes may be used with them:
* ssh://[user@]host.xz[:port]/path/to/repo.git/
* git://host.xz[:port]/path/to/repo.git/
* http[s]://host.xz[:port]/path/to/repo.git/
* ftp[s]://host.xz[:port]/path/to/repo.git/

An alternative scp-like syntax may also be used with the ssh protocol:
    [user@]host.xz:path/to/repo.git/

This syntax is only recognized if there are no slashes before the first colon. This helps differentiate a local path that contains a colon. For example the local path foo:bar could be specified as an absolute path or ./foo:bar to avoid being misinterpreted as an ssh url.

**Comment by TheSnoozer** [comment]
I fixed this now.
Everything with the pattern "^([a-zA-Z0-9_.+-])+@(.*)|^\\[([^\\]])+\\]:(.*)" will now be treated as "scm-like" and thus won't be searched for password credentials....not sure if someone would store credentials in scm/ssh but in this case I would rather say its a wrong usage of ssh and thus ignore the case where one actually could have credentials inside scm-like syntax....
