### ISSUE TITLE
No properties exposed to Maven build when generating properties file ?

### ISSUE THREAD

**Issue by HereThereBeMonsters** [ktoso/maven-git-commit-id-plugin#275]
Thanks for that great plugin! 

I am using it to generate a properties file using the `generateGitPropertiesFile` option set to `true`.

However I also would like to have access to the properties in the rest of my build process, in order to include the git tag in some final artifacts name for example with the shade plugin : 

```
<shadedClassifierName>r${git.commit.id}-executable</shadedClassifierName>
```
However it seems that when the Git plugin is generated the properties file the properties are not exposed any more. When I set the option to false, the above works, but when I set it to true, the `${git.commit.id}` is not resolved.

**Is it possible to have both the properties file generated AND to have the properties exposed in the Maven build ?**

If not, is it intentional ?

**Comment by mkrivan** [comment]
Dear Pier try with the master branch. Approx month ago i made contribution
for this among some small others and it is already merged.

Pierre Henry <notifications@github.com> ezt írta (időpont: 2017. febr. 24.,
Pén 9:48):

**Comment by gembin** [comment]
```xml
<generateGitPropertiesFile>true</generateGitPropertiesFile>	
<generateGitPropertiesFilename>${project.build.directory}/git.properties</generateGitPropertiesFilename>
```

But the file is written to a wrong path

```
[info] Writing properties file to [ /Users/xxxx/source-repo/my-prj/Users/xxxx/dev/source-repo/my-prj/target/classes/git.properties ] ...
```

**Comment by TheSnoozer** [comment]
The ``<injectAllReactorProjects>true</injectAllReactorProjects>`` should to the trick to expose the properties to the maven build cycle.

**Comment by TheSnoozer** [comment]
Tested this [here](https://github.com/TheSnoozer/git-commit-id-debugging) with the following config:
```
<plugin>
  <groupId>pl.project13.maven</groupId>
  <artifactId>git-commit-id-plugin</artifactId>
  <version>2.2.2</version>
  <executions>
    <execution>
      <goals>
        <goal>revision</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <prefix>git</prefix>
    <dotGitDirectory>${project.basedir}/.git</dotGitDirectory>
    <injectAllReactorProjects>true</injectAllReactorProjects>
    <generateGitPropertiesFile>true</generateGitPropertiesFile>
    <generateGitPropertiesFilename>target/classes/git.properties</generateGitPropertiesFilename>
  </configuration>
</plugin>

<plugin>
	<artifactId>maven-antrun-plugin</artifactId>
	<version>1.8</version>
	<executions>
		<execution>
			<phase>package</phase>
			<configuration>
				<target>
          <echo>Git-Infos: ${git.commit.id}</echo>
				</target>
			</configuration>
			<goals>
				<goal>run</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

-> works as expected and outputs:
```
     [echo] Git-Infos: 0bc3ae7cad21fb297dabd6eeb374b76dfeb60f8e
```

Also works when setting ``<generateGitPropertiesFile>false</generateGitPropertiesFile>`` (that would be what I expect....we should be able to expose properties even though  we don't specifically need a properties file).

~ Closing ~

**Comment by mireczatko** [comment]
hi @TheSnoozer, I have same problem, your example with maven 3.3.9, outputs:
`[echo] Git-Infos: ${git.commit.id}`
