### ISSUE TITLE
Feature: alphabetically sort properties in generated file

### ISSUE THREAD

**Issue by edysli** [ktoso/maven-git-commit-id-plugin#284]
Currently the plugin (version 2.2.2) writes properties apparently in no specific order. This makes it fairly tedious for a human to read and find a specific property. For example, here is what I got today (keys only):

```
git.build.user.email
git.build.host
git.dirty
git.remote.origin.url
git.closest.tag.name
git.commit.id.describe-shor
git.commit.user.email
git.commit.time
git.commit.message.full
git.build.version
git.commit.message.short
git.commit.id.abbrev
git.branch
git.build.user.name
git.closest.tag.commit.count
git.commit.id.describe
git.commit.id
git.tags
git.build.time
git.commit.user.name
```

I think it would be more readable if the properties were sorted alphabetically by their keys, like this:

```
git.branch
git.build.host
git.build.time
git.build.user.email
git.build.user.name
git.build.version
git.closest.tag.commit.count
git.closest.tag.name
git.commit.id
git.commit.id.abbrev
git.commit.id.describe
git.commit.id.describe-shor
git.commit.message.full
git.commit.message.short
git.commit.time
git.commit.user.email
git.commit.user.name
git.dirty
git.remote.origin.url
git.tags
```

**Comment by ktoso** [comment]
If you'd like to see this included the best way to get it done would be to help out, would you be interested in submitting a PR with this?

**Comment by edysli** [comment]
I could do that. :grinning: Should it be configurable or the default behaviour?

**Comment by ktoso** [comment]
Perhaps default, we have too many options already

**Comment by edysli** [comment]
I'm thinking about using [java-ordered-properties](https://github.com/etiennestuder/java-ordered-properties) for this. Is it OK to introduce a new dependency?

**Comment by TheSnoozer** [comment]
Technically this only has a visual value if someone actually looks into the file...

But why introduce another dependency? Whats wrong with Collections.sort ?

**Comment by TheSnoozer** [comment]
Feature has been added!
Thanks for the input!

Will be released (sometime) with version 2.2.3

**Comment by edysli** [comment]
Oh thank you very much! That was fast! :smile: 

> Whats wrong with Collections.sort ?

You have to extend `java.util.Properties` to mess around with its internals. Therefore, you end up depending on implementation details of a class you don't own. I think composition would be a better design in this case. Anyway, it's your project so I'll leave it to you to balance design, implementation effort and dependencies... :slightly_smiling_face:

**Comment by TheSnoozer** [comment]
Mhh sure there are always advantages and disadvantages....I personally don't see a use case where the current implementation would break and if it does there are tests that hopefully ensure that the build breaks...however finds a bug can freely blame me ;-)
