### ISSUE TITLE
Generating git.properties and renaming packaged artifact simultaneaously

### ISSUE THREAD

**Issue by seainside75** [ktoso/maven-git-commit-id-plugin#286]
Hello,

as subject suggests, I'm trying to configure the plug-in in order to generate the git.properties file
and the final jar/war reporting some of git properties in the same "mvn package" run.
it seems that they are alternatives and uniquely driven by the following configuration option.

<generateGitPropertiesFile>false</generateGitPropertiesFile>

Is it so?
Am I missing something else?

Thanks in advance

**Comment by TheSnoozer** [comment]
``
<configuration>
                    <dotGitDirectory>${project.basedir}/.git</dotGitDirectory>
                    <generateGitPropertiesFile>true</generateGitPropertiesFile>
                    <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>
</configuration>
``
If you for some reason want to include a version number inside the generated jar-file (basically want to use git-properties in your maven-file) you also need to tell the plugin to expose them to the maven build cycle:
``<injectAllReactorProjects>true</injectAllReactorProjects>``
