### ISSUE TITLE
Feature request: git repo information

### ISSUE THREAD

**Issue by n2taylor** [ktoso/maven-git-commit-id-plugin#29]
Great plugin! Would be even better if I could see some of the information from `git remote -v show`, specifically the URL and remote name. That way I could see if a build was deployed from a Github fork or from the main repo.

**Comment by TheSnoozer** [comment]
Hi,
this property was introduced with https://github.com/ktoso/maven-git-commit-id-plugin/commit/9fd14be7786579351e84d5e6e9cabc7bb2614077 and should be included in v2.1.5

The resulting property looks like this:
```
git.remote.origin.url=git@github.com\:TheSnoozer/maven-git-commit-id-plugin.git
```

For everybody who does not like to expose such sensitive data, the property can also be excluded
```
          <excludeProperties>
            <excludeProperty>git.remote.origin.url</excludeProperty>
          </excludeProperties>
```
