### ISSUE TITLE
Add Travis Oracle JDK9 and JDK7

### ISSUE THREAD

**Issue by TheSnoozer** [ktoso/maven-git-commit-id-plugin#292]
https://travis-ci.org/ktoso/maven-git-commit-id-plugin/jobs/252198370

```
$ jdk_switcher use oraclejdk9

Sorry, but JDK 'oraclejdk9' is not known.

The command "jdk_switcher use oraclejdk9" failed and exited with 1 during .

Your build has been stopped.
```
see:
https://github.com/travis-ci/travis-ci/issues/5520

**Comment by ktoso** [comment]
Yeah I still don't know how to get JDK9 easily on travis... It's also blocking some other projects that I'm working on so perhaps I'll get to find out soon enough. Thanks for the ticket!

**Comment by TheSnoozer** [comment]
it seems that travis doesn't have the option to switch to java 9 yet since java 9 isn't officially released.
Just wanted to open a ticket so it can't get lost....;-)

**Comment by ktoso** [comment]
The tricky thing is that the other project I work on is kind of pre-requisite for a stable JDK9 :D https://github.com/reactive-streams/reactive-streams-jvm

We'll get it solved soon enough though :)

**Comment by TheSnoozer** [comment]
Java 9 is stable - highly depends on your point of view of "stable" :')

**Comment by TheSnoozer** [comment]
https://github.com/junit-team/junit5/blob/master/.travis.yml would be a workaround to get Java 9-EA.

**Comment by ktoso** [comment]
Oh nice, thanks for finding that way :) I guess yeah, manual but it'll work :)
I'll give you kudos in the reactive-streams repo (that's what's going to become JDK9's java.util.concurrent.Flow :-))

**Comment by TheSnoozer** [comment]
Hack your life ;)
And absolutely no problem took me 5 mins to find that one ;)

**Comment by ktoso** [comment]
Hah, when I was looking could not find anything that actually worked for a long time ;)

**Comment by TheSnoozer** [comment]
Well this seems to become very interesting....
Oracle seemed to have removed the Oracle 7 binaries (http://www.webupd8.org/2017/06/why-oracle-java-7-and-6-installers-no.html) and travis currently seem to have some issues with oraclejdk7 (https://github.com/travis-ci/travis-ci/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20oraclejdk7)

https://github.com/travis-ci/travis-ci/issues/7884
https://github.com/travis-ci/travis-ci/issues/7964

For now I'll leave it as is and see how it goes...
At least some libraries needs updating for java 9.

**Comment by TheSnoozer** [comment]
Travis currently doesn't work with oraclejdk7.
See: https://travis-ci.org/TheSnoozer/maven-git-commit-id-plugin/jobs/256031572

Switched to openjdk7 for now

**Comment by TheSnoozer** [comment]
As a side note:
Oraclejdk7 is still broken and I would assume it remains broken since the official download was removed :-(

In general the plugin works fine with Java 9:
https://travis-ci.org/TheSnoozer/maven-git-commit-id-plugin/builds/260818595

What needs to change can be reviewed here:
https://github.com/ktoso/maven-git-commit-id-plugin/compare/master...TheSnoozer:travis
TDLR:
we had been using a package from ``mockito.internal`` in our tests :')

Will make a PR about this after release of 2.2.3

**Comment by TheSnoozer** [comment]
See https://github.com/ktoso/maven-git-commit-id-plugin/pull/308
