### ISSUE TITLE
Might be nice to show which version of the plugin requires which maven version

### ISSUE THREAD

**Issue by j256** [ktoso/maven-git-commit-id-plugin#295]
Right now I'm having problems because our production CI boxes are stuck on maven 3.0.5 because they are behind on linux releases.  It would be nice to know which versions of the maven git plugin required which versions of maven so I would know which version of the plugin that I should use.

Looks like 2.1.12 supports mvn below 3.1.1 for the record.

Thanks much for it.

**Comment by TheSnoozer** [comment]
I did a really quick test about this...see 
[compatibility-results.txt](https://github.com/ktoso/maven-git-commit-id-plugin/files/1148628/compatibility-results.txt)

Can you check if 2.1.13 is also working for you?
Based on what my results suggest this would be the last working version with this rather old maven version.
Please note that if you rely on Java 1.6 the last supported version would be ``2.1.15``. however in combination with an old maven it rather would be version 2.1.13....

For testing purposes:
* Git-Commid-Id-Plugin version comes from https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22pl.project13.maven%22%20AND%20a%3A%22git-commit-id-plugin%22
* Maven versions: https://archive.apache.org/dist/maven/maven-3/

```bash
#!/bin/bash
for mavenBasePath in /usr/share/maven-3*
do
  echo "============================================"
  ${mavenBasePath}/bin/mvn --version
  echo ""
  # ${file}/bin/mvn clean initialize -Pdemo
  for pluginVersion in 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0.2 2.0.3 2.0.4 2.1.0 2.1.1 2.1.2 2.1.3 2.1.4 2.1.5 2.1.6 2.1.7 2.1.8 2.1.10 2.1.11 2.1.12 2.1.13 2.1.14 2.1.15 2.2.0 2.2.1 2.2.2
  do
    # echo ${pluginVersion}
    ${mavenBasePath}/bin/mvn pl.project13.maven:git-commit-id-plugin:${pluginVersion}:revision > /dev/null
    rc=$?;
    if [[ $rc != 0 ]]; then
      echo "pl.project13.maven:git-commit-id-plugin:${pluginVersion} is NOT compatible";
    else
      echo "pl.project13.maven:git-commit-id-plugin:${pluginVersion} is compatible"
    fi
  done
done
```

**Comment by j256** [comment]
I confirmed that 2.1.13 also works.  Thanks much!

**Comment by TheSnoozer** [comment]
Ok perfect I'll add this to the Readme :-)

Thanks for the input / bug ticket!
