### ISSUE TITLE
git-commit-id-plugin removes project properties generated by other plugins

### ISSUE THREAD

**Issue by cbuschka** [ktoso/maven-git-commit-id-plugin#310]
We love the git-commit-id-plugin and use it in combination with the jacoco plugin. The jacoco plugin creates a property which must be included in surefire runs as argLine.

When property filtering is active in the git-commit-id-plugin and generating a properties file is disabled, the git-commit-id-plugin operates on the maven project properties and removes all project properties not matching the patterns of <includeOnlyProperties>, including the jacoco generated property and others not created by the git-commit-id-plugin.

Workaround: Disable property filtering.

I created an example setup to reproduce the issue at https://github.com/cbuschka/maven-git-commit-id-plugin-issue310.

**Comment by TheSnoozer** [comment]
see https://github.com/ktoso/maven-git-commit-id-plugin/pull/311

**Comment by TheSnoozer** [comment]
Thanks again for reporting and fixing this!
Was merged with #311
