### ISSUE TITLE
No properties exposed to Maven build for packaging "pom"

### ISSUE THREAD

**Issue by mireczatko** [ktoso/maven-git-commit-id-plugin#321]
No properties are exposed to Maven build for packaging "pom" After changing packaging to "jar" everything work as expected
maven `3.3.9`
maven-git-commit-id-plugin `2.2.3`

this bug seems to be introduced with version `1.9` of the plugin

**Comment by TheSnoozer** [comment]
Hi,
thanks for reporting your issue here.
This is indeed expected behaviour.

From the [Readme](https://github.com/ktoso/maven-git-commit-id-plugin/):
```
<!--
                        this is true by default; You may want to set this to false, if the plugin should run inside a
                        <packaging>pom</packaging> project. Most projects won't need to override this property.

                        For an use-case for this kind of behaviour see: https://github.com/ktoso/maven-git-commit-id-plugin/issues/21
                    -->
                    <skipPoms>true</skipPoms>
```

Try again with `<skipPoms>false</skipPoms>` as configration for the plugin.

**Comment by mireczatko** [comment]
Ooops, I am sorry then. I didn't find the property. Thank you very much.

**Comment by TheSnoozer** [comment]
Not a problem, let me know if you still have an issue with running or configuring the plugin.
the plugin needs a bit of tweaking and configuration ;-)

not sure if there is anything that could help improve the overview and visibility of all those switches inside the readme
