### ISSUE TITLE
Maintain and update release-notes with things that have changed

### ISSUE THREAD

**Issue by TheSnoozer** [ktoso/maven-git-commit-id-plugin#324]
Github offers the really nice feature to maintain and somewhat publish release notes within it's release page:
https://github.com/ktoso/maven-git-commit-id-plugin/releases

I think this is something that can be used to tell about important features...just tested this with the latest available and it should be updated for older releases as well

TODO:
- [x] review changes for version 2.2.3 and check for anything game-breaking and update release-notes
- [x] create release-notes for version 2.2.2
- [x] create release-notes for version 2.2.1
- [x] create release-notes for version 2.2.0
- [x] create release-notes for version 2.1.15
- [x] create release-notes for version 2.1.14
- [x] create release-notes for version 2.1.13
- [x] create release-notes for version 2.1.12
- [ ] think about if it would be worth creating release-notes for older releases

Note:
this will not create any tags or modify anything in the git-repository - basically this is just giving a git tag that has been generated by the maven-release-plugin a meaning full thing attached to it :-)

**Comment by ktoso** [comment]
Awesome release notes, thanks a ton for doing that :-)

**Comment by TheSnoozer** [comment]
Not a problem :-)
Its somewhat really interesting to look into the history of this plugin and find out what went wrong and went good.

Feel free to edit / adjust them if you find any typos or want anything in particular added.
For the next releases I would just use the latest as a copy-paste template :-)

**Comment by ktoso** [comment]
Yeah sounds good - so far all good! :)

**Comment by TheSnoozer** [comment]
Just for reference:
When creating the ``2.1.13`` release-notes I accidentally put in ``v.2.1.13`` for the tag (note the extra dot). I could remove it since it didn't made any sense...

```
$ git tag -d v.2.1.13
Deleted tag 'v.2.1.13' (was f0450de)
```

**Comment by TheSnoozer** [comment]
I added release-notes until ``2.1.9`` which was released back in Feb 9, 2014. Now creating release-notes is getting tricky since not all commits have an related issue....
not sure if it would be worth to dig through the commits itself (e.g. with the compare view https://github.com/ktoso/maven-git-commit-id-plugin/compare/a9dba4a25b64ab288d90cd503785b830d2e189a2...aade0c55eea111420e357344295ee36764d75e1b)
