### ISSUE TITLE
Release 2.2.4?

### ISSUE THREAD

**Issue by TheSnoozer** [ktoso/maven-git-commit-id-plugin#333]
Not sure if we already should release a new version and thus opening this to get some more feedback (from the users of this plugin ;-)).

General question:
Should the new version 2.2.4 be released? 
The last release (2.2.3) is now about a month ago.

Only valid point why the release should be postponed if there is anything needed to fix to have this plugin run with sbt (this was asked on gitter very recently). 

General scope of the new release:
Fixed some minor things, implemented support for Maven 3.X, added some minor features...(full list https://github.com/ktoso/maven-git-commit-id-plugin/milestone/23?closed=1).

I would assign this task to myself to verify if I can deploy the plugin (if this would be ok with @ktoso).

**Comment by alexandreroman** [comment]
Any idea when 2.2.4 will be out?

**Comment by TheSnoozer** [comment]
Hi,
in fact you seem to be the first person asking for it :-)
My intent of creating this ticket is to see if someone is looking for a release...since no one responded to this so far I considered it as a silent acknowledgement of "no release is due" ;-)

However to answer your question: I would like to investigate #336 further before making any release. I hope I find some time on the weekend to look into that further. 

Once this is solved and no major bugs are being reported I would be happy to release a new version.

Unfortunately I can't provide an exact date (yet).

**Comment by djn72** [comment]
Hey,

I'd give  thumbs-up for a 2.2.4 release - I am interested in the changes to <replacementProperties> from v2.2.4 and I'd like to use them....

**Comment by TheSnoozer** [comment]
- [x] mvn release:prepare
[INFO] Checking dependencies and plugins for snapshots ...
What is the release version for "Git Commit Id Maven Plugin"? (pl.project13.maven:git-commit-id-plugin) 2.2.4: [ENTER]
What is SCM release tag or label for "Git Commit Id Maven Plugin"? (pl.project13.maven:git-commit-id-plugin) git-commit-id-plugin-2.2.4: **v2.2.4** [ENTER]
What is the new development version for "Git Commit Id Maven Plugin"? (pl.project13.maven:git-commit-id-plugin) 2.2.5-SNAPSHOT: [ENTER]

- [x] wait for travis checks to pass

- [ ] mvn release:perform

- [ ] then go to oss.sonatype.org log in there and go to the staging repositories, there will be the plugin, you have to first close and then release it if validation passed.

- [ ] close old milestone

- [x] create new milestone for new version

- [ ] publish Release-Notes

**Comment by TheSnoozer** [comment]
I just released the 2.2.4 version which should be available in a couple of hours (usually takes some time due to synchronization)

Feel free to reopen if its not available until tomorrow.

**Comment by ktoso** [comment]
Thanks for doing the release @TheSnoozer ! Seems all's good with it :)

**Comment by ktoso** [comment]
It safely made it to maven central :) http://search.maven.org/#artifactdetails%7Cpl.project13.maven%7Cgit-commit-id-plugin%7C2.2.4%7Cmaven-plugin
