### ISSUE TITLE
dotGitDirectory extrapolation breaks Maven Release Plugin

### ISSUE THREAD

**Issue by lennartj** [ktoso/maven-git-commit-id-plugin#334]
Hello there,

The GitCommitIdPlugin continuously breaks my release build (but not the standard build), due to some funky synthesis of the paths to find the ```.git``` directory in a multi-module reactor.

The release plugin operates in the top directory, and the synthesis of the .git path misfires if the MGCIP is used in submodule projects. For example: using the expression 

                        <dotGitDirectory>${project.basedir}/../.git</dotGitDirectory>

yields a directory outside (above) the reactor with the exception:

        [ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.3:revision (default) on 
        project (theSubProjectArtifactID): Could not complete Mojo execution...: 
        java.net.URISyntaxException: Illegal character in path at index 21: 
        C:/Development/rel/..\(theReactorName) -> [Help 1]

**Comment by lennartj** [comment]
To add another level of extrapolation insight, I moved to the following structure to work around the MGCIP during release:

    <properties>
                <reactorRootDir>${project.basedir}/../.git</reactorRootDir>
    </properties>

and then, later in the pom, that variable is used:

            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>2.2.3</version>
                <configuration>
                    
                    <generateGitPropertiesFile>true</generateGitPropertiesFile>
                    <generateGitPropertiesFilename>${project.build.outputDirectory}/META-INF/maven/git.properties</generateGitPropertiesFilename>
                    <format>properties</format>

                    <dotGitDirectory>${reactorRootDir}</dotGitDirectory>
                </configuration>

Running a maven build to ensure that the variable is actually used from the command line, and that the build would break since there is no dotGitDirectory in file:///C:/foobar:

      mvn -X -DreactorRootDir=file:///C:/foobar clean install > build.log

However, the build log contains the following:

    [DEBUG] Configuring mojo 'pl.project13.maven:git-commit-id-plugin:2.2.3:revision' with basic configurator -->
    [DEBUG]   (s) dotGitDirectory = C:\Development\(reactorDir)\(subprojectDir)\file:\C:\foobar

**Comment by TheSnoozer** [comment]
Hi,
thanks for reporting your problem here. I would need to investigate what is going on here...

Just for understanding:
You have a reactor-build-project and defined the git-commit-id-plugin inside one of the build, but not on the top-level?

Also could you provide a full stacktrace of the first exception
```
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.3:revision (default) on 
    project (theSubProjectArtifactID): Could not complete Mojo execution...: 
    java.net.URISyntaxException: Illegal character in path at index 21: 
```
?
Based on the path you are providing:
- Are you using windows 10?
- What Java version?
- What Maven version?
- Is this a private project or something that I potentially could checkout to reproduce this myself?

I sometimes still would argue that the release-plugin tries to achieve too much stuff with a single command...but that's a different story...

**Comment by lennartj** [comment]
Yes - I have an assembly (sub)project within the reactor where I use the git.properties file to perform resource filtering. Imagine something like:

     #!/bin/bash
     #
     #
     # Project version: ${project.version}
     # Built by       : ${user.name}
     # Build time     : ${git.build.time}
     # Build on       : ${git.build.host} running ${os.name} (${os.version} and ${os.arch})
     # Built using    : ${java.version}
     #
     # Version info (GIT):
     # Commit ID   : ${git.commit.id}
     # Branch:     : ${git.branch}
     # Commit time : ${git.commit.time}
     # Committed by: ${git.commit.user.name}
     #

... and some other resources as well.  I will check with some of the biz folks to release a stacktrace (will likely need to anonymize it a tad).

Java: 1.8.0_144
Maven: 3.5.0

Sorry - codebase is proprietary, but it is likely simple to reproduce. I'll be back.

**Comment by lennartj** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project (something)-reactor: Maven execution failed, exit code: '1' -> [Help 1]
    org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal     org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project (something)-reactor:     Maven execution failed, exit code: '1'
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

    Caused by: org.apache.maven.plugin.MojoExecutionException: Maven execution failed, exit code: '1'
	at     org.apache.maven.plugins.release.PrepareReleaseMojo.prepareRelease(PrepareReleaseMojo.java:290)
	at org.apache.maven.plugins.release.PrepareReleaseMojo.execute(PrepareReleaseMojo.java:240)
	at     org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more

    Caused by: org.apache.maven.shared.release.ReleaseExecutionException: Maven execution failed, exit code: '1'
	at org.apache.maven.shared.release.phase.AbstractRunGoalsPhase.execute(AbstractRunGoalsPhase.java:91)
	at org.apache.maven.shared.release.phase.RunPrepareGoalsPhase.execute(RunPrepareGoalsPhase.java:44)
	at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:234)
	at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:169)
	at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:146)
	at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:107)
	at org.apache.maven.plugins.release.PrepareReleaseMojo.prepareRelease(PrepareReleaseMojo.java:286)
	... 23 more

    Caused by: org.apache.maven.shared.release.exec.MavenExecutorException: Maven execution failed, exit code: '1'
	at org.apache.maven.shared.release.exec.ForkedMavenExecutor.executeGoals(ForkedMavenExecutor.java:151)
	at org.apache.maven.shared.release.exec.AbstractMavenExecutor.executeGoals(AbstractMavenExecutor.java:114)
	at org.apache.maven.shared.release.phase.AbstractRunGoalsPhase.execute(AbstractRunGoalsPhase.java:85)
	... 29 more

**Comment by TheSnoozer** [comment]
Thanks for all the infos.
Interestingly the stacktrace doesn't contain the initial error:
```
 java.net.URISyntaxException: Illegal character in path at index 21: 
    C:/Development/rel/..\(theReactorName) -> [Help 1]
```

Was this executed with cygwin?

Regardless I'll prepare https://github.com/TheSnoozer/git-commit-id-debugging which is a reactor-project for testing purposes.
In general what I got from this ticket (please correct me if I misunderstood anything):

Inside a (random) submodule I would configure git-commit-id-plugin to perform some resource-filtering on a file like this:
```
#!/bin/bash
 #
 #
 # Project version: ${project.version}
 # Built by       : ${user.name}
 # Build time     : ${git.build.time}
 # Build on       : ${git.build.host} running ${os.name} (${os.version} and ${os.arch})
 # Built using    : ${java.version}
 #
 # Version info (GIT):
 # Commit ID   : ${git.commit.id}
 # Branch:     : ${git.branch}
 # Commit time : ${git.commit.time}
 # Committed by: ${git.commit.user.name}
 #
```

Based on my understanding right now it breaks inside the submodule once I do a mvn release on the top-level.

Inside the submodule the .git is configured as the following:
``<dotGitDirectory>${project.basedir}/../.git</dotGitDirectory>``

**Comment by lennartj** [comment]
Yup. Correct.

**Comment by TheSnoozer** [comment]
Ok, I think I have recreated the basic setup (but currently unable to reproduce the issue)

see: https://github.com/TheSnoozer/git-commit-id-debugging/commits/master

- The parent pom sets ``maven-release-plugin`` to ``2.5.3`` via ``pluginManagement`` - version based on the log of one of the tickets this is what you use
- Inside submodule-one I have defined everything needed for ``git-commit-id-plugin`` where the version ``2.2.3`` is being used (defined in parent pom as property) - version based on the log of one of the tickets this is what you use
- Inside submodule-one I have created the given [sample.bash](https://github.com/TheSnoozer/git-commit-id-debugging/blob/master/submodule-one/src/main/resources/sample.bash) that is being [filtered by the pom from submodule-one](https://github.com/TheSnoozer/git-commit-id-debugging/blob/master/submodule-one/pom.xml#L21)

So far I could execute ``mvn release:clean release:prepare`` on the aggregator-pom-level  without any issues (tags created and published).

For ``mvn org.apache.maven.plugins:maven-release-plugin:2.5.3:perform -DconnectionUrl=scm:git:git@github.com:TheSnoozer/git-commit-id-debugging.git -Dtag=git-commit-id-plugin-debugging-0.0.1`` only the deploy to sonatype fails (as expected) - ``Return code is: 401, ReasonPhrase: Unauthorized.``

Current Test-Environment:
```
$ mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T15:39:06-04:00)
Maven home: /usr/share/maven-3.5.0
Java version: 9.0.1, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-9-oracle
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-96-generic", arch: "amd64", family: "unix"
```

```
$ java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

Questions:
- Can the issue be reproduced on different environments (linux, windows, mac)?
- Is there anything in the minimalistic setup different?
- Does the windows instance has cygwin installed?
- Can the issue be reproduced with ``mvn release:clean release:prepare``?
- Can the issue be reproduced with the minimalistic setup?

**Comment by lennartj** [comment]
I am using a release command on the form

    mvn -DpushChanges=false -DautoVersionSubmodules=true -DreleaseVersion=3.0.1 -DdevelopmentVersion=3.0.2-SNAPSHOT -Dtag=(theProductName)-3.0.1 release:prepare

Moreover, paths in Java tend only to be complicated when running on Windows OS (i.e. when the path separator char can mimic as the standard java escape char '\'). I am doubtful this would be a problem in Linux and Mac OS environments where path separators are less likely to be confused with escape chars.

**Comment by TheSnoozer** [comment]
I can not reproduce this with windows:
```
git clone git@github.com:TheSnoozer/git-commit-id-debugging.git
cd git-commit-id-debugging
mvn release:clean release:prepare

....
[INFO] Executing: cmd.exe /X /C "git commit --verbose -F C:\Users\snooozer\AppData\Local\Temp\maven-scm-1027518959.commit pom.xml submodule-one\pom.xml submodule-two\pom.xml"
[INFO] Working directory: C:\Users\snooozer\Downloads\git-commit-id-debugging
[INFO] Executing: cmd.exe /X /C "git symbolic-ref HEAD"
[INFO] Working directory: C:\Users\snooozer\Downloads\git-commit-id-debugging
[INFO] Executing: cmd.exe /X /C "git push git@github.com:TheSnoozer/git-commit-id-debugging.git refs/heads/master:refs/heads/master"
[INFO] Working directory: C:\Users\snooozer\Downloads\git-commit-id-debugging
[INFO] Release preparation complete.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Git Commit Id Plugin Maven Mojo Debugging .......... SUCCESS [04:26 min]
[INFO] submodule-one ...................................... SKIPPED
[INFO] submodule-two ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:26 min
[INFO] Finished at: 2017-10-26T01:01:25+02:00
[INFO] Final Memory: 14M/489M
[INFO] ------------------------------------------------------------------------
```

Environment:
```
> java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

```
>mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: C:\apache\maven-3.5.0\bin\..
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jre1.8.0_151
Default locale: en_US, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

(Open) questions for your project/setup:
- Is there anything in the minimalistic setup different?
- Does the windows instance has cygwin installed?
- Can the issue be reproduced with mvn release:clean release:prepare?
- Can the issue be reproduced with the minimalistic setup?

**Comment by TheSnoozer** [comment]
Just a thought (since the exception is related):
Based on the initial Exception that was reported this might be related to https://github.com/ktoso/maven-git-commit-id-plugin/issues/305 or https://github.com/ktoso/maven-git-commit-id-plugin/issues/274 or even https://github.com/ktoso/maven-git-commit-id-plugin/issues/258.

Based on my previous questions I would also ask for the following:
- Could you provide the censored version of ``git remote -v``? It might be helpfull and needed to ensure that special characters are not being replaced - feel free though to replace anything else (e.g. replace all alphabetic characters with anything unrelated)
- Could you provide a stacktrace of the initial ``java.net.URISyntaxException: Illegal character in path at index 21: `` Exception? Unfortunately the one provided does not contain this exception
- Just for double checking: Does the normal build works without any issues and uses the plugin as well?
- Is this a single git-repo or anything special (e.g. contains submodules, symlinks)?

**Comment by TheSnoozer** [comment]
Hi @lennartj could you please provide further information so I might be able to get this fixed properly?
I'm currently suspecting a bug inside the handling of remote url's so the most helpful thing would be a  censored version of ``git remote -v``.

Thanks!

**Comment by TheSnoozer** [comment]
Assuming fixed.
Feel free to reopen with the requested information if the problem is still present.
