### ISSUE TITLE
Create an Issue Template

### ISSUE THREAD

**Issue by TheSnoozer** [ktoso/maven-git-commit-id-plugin#337]
https://help.github.com/articles/creating-an-issue-template-for-your-repository/

Example:
https://github.com/gradle/gradle/blob/master/.github/ISSUE_TEMPLATE.md

We should at least ask for the following:
```
### Expected Behavior
- Briefly outline what the plugin should do

### Current Behavior

### Steps to Reproduce (for bugs only)
- Include the **full** configuration of the plugin
- Is there a (public) project where this issue can be reproduced?
- Are there any stack-traces or any error messages? If yes please provide them

### Environment (for bugs only)
- What plugin version is being used (if not included in the full configuration)
- What Java-Version is being used (please include details about oracle-jdk VS open-jdk)
- What Maven-Version is being used (output of ``mvn --version``)
- What Operating System is being used (on Linux run ``lsb_release -a``)
- Where is maven being executed (e.g. inside Windows Terminal, Powershell, Git Bash, /bin/bash, ...)
- How is maven being executed (e.g. ``mvn clean deploy`` VS ``mvn deploy:deploy``)
```

**Comment by ktoso** [comment]
I think they don't really work well in practice.. people just ignore it, and you get even more noise.

But let's try if you think it could help us here -- we'll see, maybe the audience for this plugin will actually fill in the details :)

**Comment by TheSnoozer** [comment]
yeah fully agree...even when asked in specific you might not get the details you need to reproduce the issue/problem

I'd say give it a try and see how it works. When people don't fill it in properly it gives me just personal reasons to handle it less responsive I guess :P

**Comment by ktoso** [comment]
Let's try, I don't mind :)
