### ISSUE TITLE
git.commit.id available to POM, but not in generated manifest

### ISSUE THREAD

**Issue by davidmichaelkarr** [ktoso/maven-git-commit-id-plugin#343]
I've followed the advice for getting the commit id into the POM, and I've verified that, but the manifest in the generated manifest just has the string "${git.commit.id}".

The following is an excerpt from my parent pom that shows the use of this plugin, and the jar and ant plugins:
```			<plugin>
				<groupId>pl.project13.maven</groupId>
				<artifactId>git-commit-id-plugin</artifactId>
				<version>2.2.3</version>
				<executions>
					<execution>
						<id>get-the-git-infos</id>
						<goals>
							<goal>revision</goal>
						</goals>
						<phase>validate</phase>
					</execution>
				</executions>
				<configuration>
					<verbose>true</verbose>
					<generateGitPropertiesFile>true</generateGitPropertiesFile>
					<failOnNoGitDirectory>true</failOnNoGitDirectory>
					<injectAllReactorProjects>true</injectAllReactorProjects>
					<dotGitDirectory>${project.basedir}/../../.git</dotGitDirectory>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<archive>
						<manifestEntries>
							<SCM-Revision>${git.commit.id}, ${gitCommit}</SCM-Revision>
						</manifestEntries>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-antrun-plugin</artifactId>
				<version>1.8</version>
				<executions>
					<execution>
						<phase>package</phase>
						<configuration>
							<target>
								<echo>Git-Infos: ${git.commit.id}, ${gitCommit}</echo>
							</target>
						</configuration>
						<goals>
							<goal>run</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

The reason you see both "${git.commit.id}" and "${gitCommit}" is that I also have this property setting in an earlier "properties" block:
```		<gitCommit>${git.commit.id}</gitCommit>```

When I run the build, I see this in the output:
```
[INFO] --- maven-antrun-plugin:1.8:run (default) @ usl-shared ---
[INFO] Executing tasks

main:
     [echo] Git-Infos: fdf7abe874a0a54f580aec96da366c168446378c, fdf7abe874a0a54f580aec96da366c168446378c
```

However, when I look at the generated manifest in the resulting jar file, it shows this:
```
SCM-Revision: ${git.commit.id}, ${git.commit.id}
```

What might I be doing wrong?

**Comment by TheSnoozer** [comment]
Hi,
thanks for reporting your problem here. Mhh at first glance the plugin is working fine. In particular the fact that you can see the properties inside the maven-antrun-plugin tells me that something else might not working properly. Just to be on the safe side I have tested this exact same configuration and it seems to work fine with a sample project.

Could you please provide further details on the following:
- what Java-Version is being used (please include details about oracle-jdk VS open-jdk)
- what Maven-Version is being used (output of ``mvn --version``) -->
- in what context maven is being executed (e.g. inside Windows Terminal, Powershell, Git Bash, /bin/bash, ...) ?
- how maven is being executed (e.g. ``mvn clean deploy`` VS ``mvn deploy:deploy``)
- could you provide further information about the specific ``maven-jar-plugin`` version that is being used for your build (this should be visible inside the log)

**Comment by davidmichaelkarr** [comment]
I agree that it appears that this plugin is likely working fine.  However, it just seems odd that the maven-jar-plugin could fail to do something that is really very basic.  I had initially posted this on SO: https://stackoverflow.com/questions/47272026/git-commit-id-placed-into-pom-memory-doesnt-go-into-manifest .

```Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T00:58:13-07:00)
Java version: 1.8.0_152, vendor: Oracle Corporation
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0```

I'm running "mvn install" from a bash shell.

I'm now specifying version 3.0.2 of the maven-jar-plugin.

**Comment by TheSnoozer** [comment]
This environment don't yield anything obvious that would cause this particular behavior.
As stupid as it may sound, but I'm suspecting that your MANIFEST.MF gets overwritten.

Here is what I would suggest to do:
1.
Verify that src/main/resources or any other folder from the resources contains a MANIFEST.MF-file (after a `mvn clean` there should be no result for `find . -iname "MANIFEST.MF"`). If this yields any result the resource-file is not getting filtered and thus leaving an unresolved variable behind.

2. I would check if this behavior can be reproduced with other properties. I would keep it stupid and simple and would add something static to the manifest generation:
```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-jar-plugin</artifactId>
  <version>2.2.3</version>
  <configuration>
    <archive>
      <manifestEntries>
        <mode>development</mode>
        <SCM-Revision>${git.commit.id}, ${gitCommit}</SCM-Revision>
      </manifestEntries>
    </archive>
  </configuration>
</plugin>
```

3.
Does the jar contains the ``git.properties``-file that contains all the generated properties?


If you could provide a repository where I can reproduce this issue I think it would help a lot. As starter you could use the repo from https://github.com/TheSnoozer/git-commit-id-debugging

**Comment by davidmichaelkarr** [comment]
I did a clean, then searched for MANIFEST.MF.  Not found.

I changed it to this:
```						<manifestEntries>
						    <stuff>somestuff</stuff>
							<SCM-Revision>${git.commit.id}, ${gitCommit}</SCM-Revision>
						</manifestEntries>```

Got this in the final manifest:
```SCM-Revision: ${git.commit.id}, ${git.commit.id}
stuff: somestuff```

No, the jar doesn't have the git.properties file, but it was stored in target/classes.

I'll try building a test case for this tomorrow.

**Comment by davidmichaelkarr** [comment]
It occurs to me that it's significant that the git.properties file is in target/classes, but it's not in the jar file.  Doesn't that mean that the file was generated after the jar file was created, which implies that those properties were set after the jar file was generated, making the behavior we're seeing understandable?  Is this just a "phase" problem?

**Comment by TheSnoozer** [comment]
Interesting observation....this indeed would explain this particular behaviour and having unresolved properties inside the manifest file. 
Based on your configuration you posted the maven-git-plugin should be executed during `<phase>validate</phase>` which is the first phase of [Default Lifecycle](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference).
I would in particular watch the log when the git-plugin is being executed and when the assembly of the jar happens. Do you use any plugins that may alter the jar (thinking of proguard, shading,...)?

Potentially change the final name and see what happens
```
 <packaging>jar</packaging>
 <build>
   <finalName>WhatEverYouLike</finalName>
 </build>
```

I would expect that the generated git-properties file is inside the artifact. The presence of the property file and properties available via ant-run is a clear indicator that the plugin is working, but something during the packing of the jar doesn't pick this up...

**Comment by davidmichaelkarr** [comment]
I tried running with "-X".  I searched through the output, and I couldn't even tell where it was creating the jar. I didn't see "maven-jar-plugin" anywhere in the output.

We do use the bundle plugin, which manipulates the jar manifest.  That's about all that might be suspect. Our packaging type is bundle, not jar.  It seems plausible this has something to do with the problem.

I changed the finalName, which changed the name of the jar, but it had the same symptoms.

**Comment by davidmichaelkarr** [comment]
And I confirmed that when I temporarily change the packaging to "jar", the property substitution works properly.  I lose all of our required osgi properties, but at least this tells us for sure that the bundle aspect is what's causing this problem.

**Comment by TheSnoozer** [comment]
Ahh ok. So this confirms my initial assumptions that something is messing with the manifest.

Thanks for the clarification.
is this the bundle-plugin from http://felix.apache.org/components/bundle-plugin/ ?
It seems that you can add properties there as well:
```xml
<plugins>
  <plugin>
      <groupId>org.apache.felix</groupId>
      <artifactId>maven-bundle-plugin</artifactId>
      <version>1.4.0</version>
      <extensions>true</extensions>
      <configuration>
          <instructions>
              <SCM-Revision>${git.commit.id}, ${gitCommit}</SCM-Revision>
          </instructions>
      </configuration>
  </plugin>
</plugins>
```

what happens if you add the ``<SCM-Revision>${git.commit.id}, ${gitCommit}</SCM-Revision>`` at this level? based on the [docs of the maven bundle plugin](https://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html) ``Any instruction that starts with a capital letter will appear in the resulting bundle's manifest file; the value for the header will either be copied, augmented, or generated by BND depending on the instruction.``

**Comment by davidmichaelkarr** [comment]
I was writing the response confirming that this works when I saw your response about this appear. :)

**Comment by TheSnoozer** [comment]
Perfect timing I guess ;)
So having added this added as instruction for the maven-bundle-plugin did the trick and solved the issue?

I'm not quite familiar with that plugin and can't test it right now :P

**Comment by davidmichaelkarr** [comment]
Yes, I confirmed that just adding this instruction to that, and removing my maven-jar-plugin reference, got me what I needed.

I just ended up with the following:

```				<plugin>
					<groupId>org.apache.felix</groupId>
					<artifactId>maven-bundle-plugin</artifactId>
					<version>${felix.version}</version>
					<extensions>true</extensions>
					<configuration>
						<instructions>
							<SCM-Revision>${git.commit.id}</SCM-Revision>
						</instructions>
					</configuration>
				</plugin>
```

**Comment by TheSnoozer** [comment]
Ok glad it got sorted.
I'm closing this issue then :-)
