### ISSUE TITLE
Drop support for Java 7?

### ISSUE THREAD

**Issue by TheSnoozer** [ktoso/maven-git-commit-id-plugin#346]
Just a general question:
Would it be safe to drop the support for Java 7?
Who is using this now rather old Java (hopefully nearly everyone has upgraded to at least java 8)?

Based on [Oracle Java SE Support Roadmap](http://www.oracle.com/technetwork/java/eol-135779.html) Java 7 does not get any Public Updates, Premier Support ends Jul 2019; Extended Support ends Jul 2022. 

| Release | GA Date | Premier Support Until | Extended Support Until | Sustaining Support |
| ------- | --------- | ---------------------- | ------------------------ | ------------------- |
| 6 | Dec 2006 | Dec 2015 | Dec 2018 | Indefinite |
| 7 | Jul 2011 | Jul 2019 | Jul 2022 | Indefinite |
| 8 | Mar 2014 | Mar 2022 | Mar 2025 | Indefinite |
| 9 (non-LTS) | Sep 2017 | Mar 2018 | Not Available | Indefinite |

Considering it is "only" covered by Premier Support for quite a while now I'm debating to just stop supporting it...maybe still to early and it should wait another year...

Main question to consider the upgrade to a new Java version:
How much is this project gaining by dropping the support?
- The main thing to consider is that this upgrade would allow the project to use more recent versions of third party libraries (e.g. jgit v4.6 moved towards 1.8 only https://bugs.eclipse.org/bugs/show_bug.cgi?id=500059)
- I wouldn't expect crazy changes for the resources inside the project itself since I personally only see lambda expressions one key factor for java 8 and the rest is rather a more convenient call to some java functionality http://www.oracle.com/technetwork/java/javase/8-whats-new-2157071.html). However I don't see a particular thing where lambda expression would fit into this project.

Support for Java 8 and Java 9 is not debatable and should remain fully supported.
Note: Maven (https://maven.apache.org/docs/history.html) currently still supports Java 7

**Comment by ktoso** [comment]
Yes, we absolutely should drop 7 already I think.
People who are on 7 are free to remain on an old version of the plugin, as they do with their entire runtime - being on an unsupported version.

Feel free to change the build's lang level etc

**Comment by TheSnoozer** [comment]
sounds good, will drop it for next release :-)

**Comment by ktoso** [comment]
Yay :)

**Comment by laurentperez** [comment]
+1
please however do note that for POJO integration Spring 3 does not support lambdas and will never do, and its classpath loader will crash when scanning a jar with lambdas
and if you follow semver standard it should be 3.0.0 because it won't be retrocompatble for java7 as in 2.3.0 (major minor patch)

**Comment by TheSnoozer** [comment]
Agree, if we change Java it should be a 3.0.0 version
