### ISSUE TITLE
Question: Is it possible to get commit count property?

### ISSUE THREAD

**Issue by moleksyuk** [ktoso/maven-git-commit-id-plugin#352]
Hi,

I don't see any property that will return commit count to head - `git rev-list HEAD --count`.
Is it possible with this plugin or not?

Thanks.

**Comment by TheSnoozer** [comment]
Hi,
thanks for your input.
Unfortunately this is not yet added to this plugin (yet), but technically it should be easily doable.

There is a Merge-Request filled with this quite recently:
https://github.com/ktoso/maven-git-commit-id-plugin/pull/345

From my standpoint this commit is pretty much what is needed as functionality, but I have requested some changes before I merge it.

I'd leave this ticket open, might need to adjust the MR myself....

**Comment by ktoso** [comment]
PR #357 solved this, thanks @TheSnoozer !
