### ISSUE TITLE
Include jenkins BUILD_NUMBER inside git properties

### ISSUE THREAD

**Issue by xiaoshao** [ktoso/maven-git-commit-id-plugin#353]
I am using this plugin for track my changes. But only the commit id is not enough. I want to add the version number in jenkins which is set in env to the git properties.

**Comment by TheSnoozer** [comment]
Are you referring to the BUILD_NUMBER that is getting populated by jenkins into the environment variables?

**Comment by xiaoshao** [comment]
yes,  I want to add the env 'BUILD_NUMBER' to the git.properties which generated by this plugin to make it easier to know the package was built by which one.

**Comment by TheSnoozer** [comment]
For me it would make sense to call it ``git.build.number`` and load it in the same method as [loadBuildHostData](https://github.com/ktoso/maven-git-commit-id-plugin/blob/master/src/main/java/pl/project13/maven/git/GitCommitIdMojo.java#L489). Should not be to hard to integrate it.
Just a side note: If it can not be found/extracted the property will be empty and there will be no validation if this property makes sense.
