### ISSUE TITLE
Use of java.net.InetAddress.getLocalHost().getHostName() can be very slow

### ISSUE THREAD

**Issue by vorburger** [ktoso/maven-git-commit-id-plugin#354]
### Expected Behavior
maven-git-commit-id-plugin should work well offline and be fast! :smile: 

### Current Behavior
The use of `java.net.InetAddress.getLocalHost().getHostName()` in `GitCommitIdMojo.loadBuildHostData` can be slow on certain networks (e.g. bad WiFi); as seen e.g. in https://github.com/vorburger/opendaylight-eclipse-setup/issues/4.  Various online posts document why that is so - it does a reverse DNS look up.

There are libraries with native equivalents; I don't know if you would consider using one of those?

Or perhaps there could simply be a property to skip `loadBuildHostData` ?

**Comment by TheSnoozer** [comment]
Hi, thanks for your report and the detailed investigation :
)
There are certain things that might take a long time with this plugin and might not be needed by all consumers.
Introducing another switch would be somewhat painfull and would be potentially needed for every property.
Plus in all honesty I think this plugin has way to many switched and tweeks already and as a result I would try to avoid to introduce another configuration option.

However I fully agree that there should be something to avoid getting stuck in any method when the data is not needed. Would https://github.com/ktoso/maven-git-commit-id-plugin/issues/185 be something that would help to solve this issue in your case?

**Comment by vorburger** [comment]
@TheSnoozer yeah a way to just exclude the `build.host` to save the `loadBuildHostData` which does that `java.net.InetAddress.getLocalHost().getHostName()` would address this, so if you want to close this as a dupe of #185 that's perfectly fine with me.

**Comment by TheSnoozer** [comment]
Alright, I think its time to get this selective running shipped! 
There are enough reasons (speedup and failures in certain extraction methods) to justify its benefits.

I'll close this as duplicate and will try to find some time to fix this (and other minor bugs) over the next days.

Thanks again for reporting this!
