### ISSUE TITLE
git.branch showing commit Id instead of branch name.  

### ISSUE THREAD

**Issue by sunnyverma88** [ktoso/maven-git-commit-id-plugin#359]
git.branch showing commit Id instead of branch name.  I am using ${git.branch} in my version.jsp to display the branch.  

Below is the what i added in POM. I am not sure if this is the issue with Maven as my local build works fine but have issue with TFS build. 

<plugin>
                    <groupId>pl.project13.maven</groupId>
                    <artifactId>git-commit-id-plugin</artifactId>
                    <version>2.1.13</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>revision</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <dotGitDirectory>${project.basedir}/../.git</dotGitDirectory>
                    </configuration>
                </plugin>

**Comment by TheSnoozer** [comment]
what does TFS reference?

**Comment by bobjana** [comment]
I faced the same issue on VSTS build agents. It turns out VSTS git checkout happens in detached mode based on last commit on particular branch, hence a commit-id in place of branch name. I implemented a workaround:

`<configuration>
<replacementProperties>
							<replacementProperty>
								<property>git.branch</property>
								<token>^.*$</token>
								
								<value>${env.BUILD_SOURCEBRANCH}</value>
								<regex>true</regex>
							</replacementProperty>
						</replacementProperties>`

Works locally as well if BUILD_SOURCEBRANCH is not available it will use the git branch

**Comment by sunnyverma88** [comment]
I tried this but it didnt work.  I have added the above as part of commit id plugin.  Or Do i have to add this maven war plugin.

**Comment by sunnyverma88** [comment]
The workaround worked . I have used sourcebrach name instead of just source branch . Also replacement property will only work if 2.2.3 version and above is used . I was using 2.1.13 initially .

**Comment by Allkoman** [comment]
@sunnyverma88 how did you solve this problem pls
