### ISSUE TITLE
Change log level to debug or add option to mute plugin output

### ISSUE THREAD

**Issue by sta-szek** [ktoso/maven-git-commit-id-plugin#360]
Is there any way to mute plugin?

If not, please change log level to debug or add option to mute plugin output.
My proposal is to switch logging to debug or make `<verbose>false</verbose>` excluding INFO logs.
Or add additional `<logHell>false</logHell>` :) which will exclude those logs.

### Expected Behavior
one of given:
* no logs are present when performing `mvn install` and others...
* logs are on debug level

### Current Behavior
lot of unnecessary logs...

**Comment by TheSnoozer** [comment]
I'm not quite sure what the issue is here. When setting ``<verbose>false</verbose>`` the output looks like the following:
```
[INFO] ------------------------------------------------------------------------
[INFO] Building Git Commit Id Maven Plugin 2.2.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ git-commit-id-plugin ---
[INFO] Deleting /home/stefan/workspace/maven-git-commit-id-plugin/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ git-commit-id-plugin ---
[INFO] 
[INFO] --- git-commit-id-plugin:2.2.5-SNAPSHOT:revision (get-the-git-infos) @ git-commit-id-plugin ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ git-commit-id-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
```

Please provide the following:
- include the **full** configuration of the plugin
- is there a (public) project where this issue can be reproduced? or at least try to reproduce the issue with the plugin itself (e.g. ``mvn clean install && mvn clean package -Pdemo -Dmaven.test.skip=true``). Note configuration would need to be adjusted to ``<verbose>false</verbose>``.

**Comment by TheSnoozer** [comment]
Feel free to reopen with an example where I can reproduce this.

**Comment by matthewmcgarvey** [comment]
Just a note to anyone that comes looking for this in the future, spring-boot turns verbose to true so you need to set it back to false
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-starters/spring-boot-starter-parent/pom.xml#L148

**Comment by TheSnoozer** [comment]
Thanks for the additional comment!
Is there anything this plugin should change? 
It rather seems for me that we should create a PR to spring-boot to set the flag there?

**Comment by matthewmcgarvey** [comment]
Looking at the blame for the file, it was set up 6 years ago and hasn't been touched since.  Maybe they would accept the PR?
