### ISSUE TITLE
Usage without .git directory (in Docker)? [question]

### ISSUE THREAD

**Issue by moriarty** [ktoso/maven-git-commit-id-plugin#361]
I have a question, and am looking for suggestion for the best approach to use this plugin in combination with Docker where the .git directory is not available at compile time.

It works fine, when cloning the git repository in a Dockerfile with Docker... but this has it's own issues, so it would be preferable to use Docker "COPY" and/or "ADD" to get the required bits into the docker image.
When "docker build" is called, it is in the git repository, and part of a Jenkins pipeline step. So I think the required information for this plugin is available.

### Expected Behavior

I'm looking to "dockerize" a large application which makes use of this plugin. However, we would like to avoid cloning the repository into the container, and just use COPY and ADD to get what needs to be into the final docker image... The project has over 70,000 commits, and the .git directory is over 500Mb... but there is also a desire to leave some things out of the final images, and take advantage of the Docker caching the COPY steps.

### Current Behavior

Works fine as long as a .git directory is present.
Cloning in a Dockefile container with --depth=1 works okay, but doesn't meet goals of leaving .git directory out of the final container. And it would be nice to take advantage of Dockers file caching.

But I'm looking for a way to continue to use this plugin without the .git directory present.
Is there one specific file(s) I could COPY into the docker container? 
Or could I generate one with a git command to a file, which would allow this plugin to be used?

Note: I'm not a maven expert at all, and this project has both c++ and java code... and I work on the C++ side, I just came across this when "Dockerizing".
I briefly looked through the documentation and couldn't see if there was an option to provide this plugin the options it needs, it seems it will want to search for this information itself.

**Comment by moriarty** [comment]
I think I just found the answer my own question:

In *./src/main/java/pl/project13/maven/git/GitCommitIdMojo.java* 
```java
  /**
   * Set this to {@code 'false'} to continue the build on missing {@code '.git'} directory.
   */
  @Parameter(defaultValue = "true")
  private boolean failOnNoGitDirectory;
```
Looks promising.

**Comment by ktoso** [comment]
Yeah, use that. Though of course the plugin can't do anything if that directory is not present.

Please let us know if we can close the ticket.

**Comment by moriarty** [comment]
Yes, setting this to false at least lets the build succeed.
I will ask my colleagues who are responsible for the module which is using this plugin, what happens if this plugin can't do anything.

So I will close this ticket.

Thanks!
