### ISSUE TITLE
execution fails if "dotGitDirectory" is invalid and "failOnNoGitDirectory" is set to "false"

### ISSUE THREAD

**Issue by QStormDS** [ktoso/maven-git-commit-id-plugin#364]
The execution fails if "dotGitDirectory" refers to a not existing directory and "failOnNoGitDirectory" is set to "false". 

Here my configuration:
`<configuration>`
`<dotGitDirectory>D:/temp</dotGitDirectory>`
`<failOnNoGitDirectory>false</failOnNoGitDirectory>`
`<!-- ... --> `
`</configuration>`

### Expected Behavior
The execution should be skipped in that case as mentioned in the documentation:
"controls whether the plugin will fail when no .git directory is found, when set to false the plugin will just skip execution"

However, this only happens if "dotGitDirectory" is blank.

### Current Behavior
The execution fails with the following message:
"Error: Could not get HEAD Ref, are you sure you have set the dotGitDirectory property of this plugin to a valid path?"

### Steps to Reproduce (for bugs only)
**full** configuration of the plugin:

`<plugin>`
`				<groupId>pl.project13.maven</groupId>`
`				<artifactId>git-commit-id-plugin</artifactId>`
`				<version>2.2.4</version>`
`				<executions>`
`					<execution>`
`						<id>get-the-git-infos</id>`
`						<goals>`
`							<goal>revision</goal>`
`						</goals>`
`					</execution>`
`				</executions>`
`				<configuration>`
`					<dotGitDirectory>D:/temp</dotGitDirectory>`
`					<failOnNoGitDirectory>false</failOnNoGitDirectory>`
`					<prefix>git</prefix>`
`					<verbose>false</verbose>`
`					<generateGitPropertiesFile>true</generateGitPropertiesFile>`
					`<generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>`
`					<format>properties</format>`
`					<gitDescribe>`
`						<skip>false</skip>`
`						<always>false</always>`
`						<dirty>-dirty</dirty>`
`					</gitDescribe>`
`					<excludeProperties>`
`                       <excludeProperty>git.build.*</excludeProperty>`
`                       <excludeProperty>git.commit.user.*</excludeProperty>`
`                       <excludeProperty>git.commit.message.*</excludeProperty>`
`                       <excludeProperty>git.commit.time</excludeProperty>`
`                       <excludeProperty>git.commit.id.describe-short</excludeProperty>`
`                       <excludeProperty>git.remote.origin.url</excludeProperty>`
`					</excludeProperties>					`
`				</configuration>`
`			</plugin>`

error messages: Error: Could not get HEAD Ref, are you sure you have set the dotGitDirectory property of this plugin to a valid path?

### Environment (for bugs only)
plug-in version: 2.2.4
java version: java-8.0.131-win32
maven version: 3.5.0
operating system: Windows 7 Professional

**Comment by TheSnoozer** [comment]
Hi,
thanks for reporting your issue here.
I can remember I had multiple lengthy discussions on what those switched do in specific....

In general the plugin has two switches (had been asked for).
One switch to control the failure if the directory hasn't been found and one switch that controls what should happen if the plugin is unable to extract repository information during the execution.

The exception you are seeing is happening at the "extraction time" and comes from:
https://github.com/ktoso/maven-git-commit-id-plugin/blob/master/src/main/java/pl/project13/maven/git/JGitProvider.java#L94

to also ignore the exceptions from "extraction time" use the following:
```
<!-- @since 2.1.5 -->
                    <!-- true by default, controls whether the plugin will fail if it was unable to obtain enough data for a complete run, if you don't care about this, you may want to set this value to false. -->
                    <failOnUnableToExtractRepoInfo>true</failOnUnableToExtractRepoInfo>```


Suggestions on how to improve the doc are welcome.

**Comment by TheSnoozer** [comment]
Unless no further objection I close this as "no-bug".
Feel free to reopen if it does not work.
