### ISSUE TITLE
Eclipse (maybe M2E-WTP) +git-commit-id-plugin reliable interaction

### ISSUE THREAD

**Issue by lrozenblyum** [ktoso/maven-git-commit-id-plugin#366]
### Expected Behavior
When I create a new commit, I expect that maven-git-commit-id-plugin will update git.properties in the target classes 

### Current Behavior
At the moment git.properties file is not updated reliably when working in Eclipse and creating new commits (NOTE: in standalone Maven it works really fine).
Maven -> Update project could help.

### Steps to Reproduce (for bugs only)
<plugin>
			    <groupId>pl.project13.maven</groupId>
			    <artifactId>git-commit-id-plugin</artifactId>
			    <version>2.2.4</version>
			    <executions>
			        <execution>
			            <id>get-the-git-infos</id>
			            <goals>
			                <goal>revision</goal>
			            </goals>
			        </execution>
			    </executions>
			    <configuration>
			        <dotGitDirectory>${project.basedir}/.git</dotGitDirectory>
			        <prefix>git</prefix>
			        <verbose>false</verbose>
			        <generateGitPropertiesFile>true</generateGitPropertiesFile>
			        <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>
			        
			        <format>properties</format>
			        
			        <includeOnlyProperties>git.commit.id.abbrev</includeOnlyProperties>
			    </configuration>
			</plugin>

### Environment (for bugs only)
Eclipse Oxygen.3a
Oracle JDK1.6.0.45
Maven 3.3.9 (built-in into Eclipse)
Windows7
Maven is executed automatically by M2E (and possible M2E-WTP since it's a web project).

NOTE: I also tried in-memory solution (when the plug-in doesn't generate a separate file) and it also work in Eclipse not perfectly.

Thank you for any help and suggestions

**Comment by lrozenblyum** [comment]
In principle I agree that's not a huge problem.
However it is (can) be a problem when we do switch to a branch and the plug-in doesn't recognize need to generate git.properties and thus we have a crash in the web application which depends on it.

**Comment by TheSnoozer** [comment]
Fixed by https://github.com/ktoso/maven-git-commit-id-plugin/pull/385
