### ISSUE TITLE
Add a "Quick Start" section to the documentation

### ISSUE THREAD

**Issue by nhooey** [ktoso/maven-git-commit-id-plugin#376]
The documentation doesn't have a clear path to get the plugin installed and working. When evaluating a lot of plugins to see if they work properly, it's convenient to be able to just paste some simple configuration to start, to decide if it's necessary to look at other plugins.

A Quick Start section of the guide can make this much faster.

**Comment by nhooey** [comment]
When I copy the example `pom.xml` in to a new, empty Git project, Maven doesn't report the correct version, nor does it generate a properties file.

See this project:
[maven-git-commit-id-plugin-example](https://github.com/nhooey/maven-git-commit-id-plugin-example)

**Comment by TheSnoozer** [comment]
Hi, 
thanks for opening an issue here.


Unfortunately I think there is never ever a "Quick Start" section that would fullfill all needs and requirements. Builds are complex and therefore there is a need for a complex documentation.

Besides that what do you really expect from the ``mvn validate``? Based on Maven's Lifecycle Reference ``validate`` really just ``validate the project is correct and all necessary information is available.``. IMHO a ``build success`` in that regard means your project seems to be correct and all necessary information is available. 

Try to run your project with ``mvn generate-sources``
```
$ cd /tmp
$ git clone git@github.com:nhooey/maven-git-commit-id-plugin-example.git
$ cd maven-git-commit-id-plugin-example
$ mvn generate-sources
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building my-git-plugin-sample-app 0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- git-commit-id-plugin:2.2.4:revision (get-the-git-infos) @ my-git-plugin-sample-app ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.474 s
[INFO] Finished at: 2018-08-16T15:48:07-04:00
[INFO] Final Memory: 10M/65M
[INFO] ------------------------------------------------------------------------

$ find . -name "git.properties"
./target/classes/git.properties

$ cat ./target/classes/git.properties | grep "commit.id"
git.commit.id=735590cbdd7a68a028b3d7c3e28576bfefe279f2
```

**Comment by TheSnoozer** [comment]
I'm closing this. Feel free to reopen if you have further questions / comments.
