### ISSUE TITLE
Allow initialization once per run (with multiple modules)

### ISSUE THREAD

**Issue by tuukkamustonen** [ktoso/maven-git-commit-id-plugin#53]
`buildnumber-maven-plugin` has http://mojo.codehaus.org/buildnumber-maven-plugin/create-mojo.html#getRevisionOnlyOnce to fetch the details only once.

With `git-commit-id-plugin` there is no such open and each module will re-fetch the details.

I tried declaring the plugin on parent POM and setting `inherited` to false, but then `${git.*}` properties don't seem to be available on child modules (even though parent seems to successfully fetch the details).

**Comment by TheSnoozer** [comment]
Hi,
https://github.com/ktoso/maven-git-commit-id-plugin/pull/143 was merged and is included in v2.1.12. 
Thanks for the contribution.
