### ISSUE TITLE
Reveal describe details (tag name, number of commits, commit id) in their own properties

### ISSUE THREAD

**Issue by tuukkamustonen** [ktoso/maven-git-commit-id-plugin#54]
With describe returning something like 1.0.0-13-abc1234, we want each part in their separate property so we can build `finalName` with custom scheme.

Commit id is already put into separate field. Support would be needed for:

* Tag name
* Number of commits since last tag

Maybe as `git.closest.tag.name` and `git.closest.tag.commit.count` or something like that?

**Comment by TheSnoozer** [comment]
Fixed by https://github.com/ktoso/maven-git-commit-id-plugin/pull/195
