### ISSUE TITLE
The plugin fails when it can't find a revision

### ISSUE THREAD

**Issue by alexnederlof** [ktoso/maven-git-commit-id-plugin#63]
The plugin fails when it can't find a revision. I think it happend because someone amended a commit. It could also be because travis doesn't fetch all revisions.

You can reproduce the problem like this:
```bash
git clone --depth=100 --quiet --branch=branchname git://github.com/crawljax/crawljax.git
cd crawljax
git checkout -qf 8c2e0f52d27c33df5e1c4c2deec472b1e138d67a
mvn clean package -DskipTests=true
```

This results in the error:
```
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.4:revision (default) on project crawljax-core: Execution default of goal pl.project13.maven:git-commit-id-plugin:2.1.4:revision failed: Unable to calculate distance between [commit 8c2e0f52d27c33df5e1c4c2deec472b1e138d67a 1359301377 ----sp] and [commit c8c9b49da0750d39f51b282e29f70672fb657b65 1356953576 ----sp]: Missing commit a19d505b92d4e73d39ab554cff26dc59dc8e25a9 -> [Help 1]
```

[Here's an example of a failed build](https://travis-ci.org/crawljax/crawljax/builds/4412511)

I don't mind that it doesn't work, but it shouldn't break the build IMHO.

**Comment by TheSnoozer** [comment]
The latest version of the plugin has two options to bypass any kind of exception:
```
<failOnNoGitDirectory>false</failOnNoGitDirectory>
<failOnUnableToExtractRepoInfo>false</failOnUnableToExtractRepoInfo>
```

failOnUnableToExtractRepoInfo was introduced with this issue
failOnNoGitDirectory was introduced with #26

Thanks for reporting and the support to track the problem down.

**Comment by julianhyde** [comment]
Thanks @rmetzger - your workaround worked for me.
