### ISSUE TITLE
@threadSafe annotation

### ISSUE THREAD

**Issue by JesperTerkelsen** [ktoso/maven-git-commit-id-plugin#66]
We parallels builds a lot where i work, and many plugins still get a warning like below.

If this plugin is thread safe, can you please specify it as such ?

See specification here http://maven.apache.org/developers/mojo-api-specification.html

Warning from maven below.

```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that are not marked as       *
[WARNING] * @threadSafe to support parallel building.                     *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in <Projectname>
[WARNING] pl.project13.maven:git-commit-id-plugin:2.1.4
[WARNING] *****************************************************************
```

To reproduce: create a multi module project, and requst parallel execution by using the following command.

```
mvn -T 1.5C clean deploy
```

**Comment by TheSnoozer** [comment]
Hi,
first of all thanks for reporting this issue.
It's been a while since this is on the market and I just wanted to check if someone could reproduce it.
I was tring to reproduce with different -T options but was not able to get a stracktrace or any kind of other error. Furthermore I checked out the code where this stack trace occurred and it seems that we tried to access the maven project properties. Back in the days the maven project properties haven't been working with ConcurrentModification which resulted in this StackTrace.

Anayway, I just wanted to check if there is anybody out who can reproduce an error on this front.
Thanks,

**Comment by TheSnoozer** [comment]
As outlined in my previous post, "back in the days" we just accessed the maven properties. I did some research and found these related maven issues:
https://issues.apache.org/jira/browse/MNG-5493
https://issues.apache.org/jira/browse/MNG-5670
https://issues.apache.org/jira/browse/MRRESOURCES-65

This seems there was a maven issue which had been solved.
In case someone is bumping into this issue again, please let me know.

For now I would say it's save to close.

**Comment by EHJ-52n** [comment]
@TheSnoozer 

could you please specify the minimum maven version which should not have this error.

I have the following set-up:
* **maven/java/os**: 
  ```
  $ mvn --version
  OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
  Apache Maven 3.3.9
  Maven home: /usr/share/maven
  Java version: 1.8.0_121, vendor: Oracle Corporation
  Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
  Default locale: de_DE, platform encoding: UTF-8
  OS name: "linux", version: "4.8.0-51-generic", arch: "amd64", family: "unix"
  ```
* **plugin version**: 
  ```
  Execution git-commit-id of goal pl.project13.maven:git-commit-id-plugin:2.1.9:revision failed. ConcurrentModificationException
  ```
