### ISSUE TITLE
generateGitPropertiesFilename property path is always relative to the project

### ISSUE THREAD

**Issue by lev-kuznetsov** [ktoso/maven-git-commit-id-plugin#73]
Try something like

${project.build.directory}/${project.build.finalName}/WEB-INF/classes/git.properties

for generateGitPropertiesFilename, it'll create home/<...>/target/<...>/WEB-INF/classes/git.properties in your project folder.

**Comment by TheSnoozer** [comment]
This problem should be fixed and merged by now.

See: https://github.com/ktoso/maven-git-commit-id-plugin/pull/125

Thanks for reporting and helpful answers!

Feel free to reopen the issue
